### ISSUE TITLE
[Enhancement] Transparent compression of stored data

### ISSUE THREAD

**Issue by dennisbirkholz** [krakjoe/apcu#103]
It would really be nice if the apcu would allow to enable transparent compression of the serialized data which could greatly reduce the memory consumption.

**Comment by krakjoe** [comment]
The only thing that APC serializes are objects, since you already have good control over how objects are serialized in userland, I'm going to say this isn't necessary.

**Comment by dennisbirkholz** [comment]
Consider you have some tree structure containing the same class over and over again. If you put that tree structure into APC, you could greatly reduce the space consumption from the namespaced class name alone if you compress the complete serialized tree structure in one go.
So now would you implement that in userspace? The class needs to be serialization-aware for this to work but you would really only want the root object of the tree structure to compress it's data, not every node.
Just compressing the string by APC after the tree structure is serialized seems a lot easier, more general purpose and a lot more effective to me.
