### ISSUE TITLE
Ubuntu 14.04 (LTS) needs to upgrade apcu-4.0.2

### ISSUE THREAD

**Issue by themightychris** [krakjoe/apcu#108]
Ubuntu 14.04, an LTS (long-term support) release, currently still publishes apcu 4.0.2, the use of which is a surefire way to make a production web application unstable. I've had a bug report open in launchpad since October requesting the version be bumped. While the problem has been confirmed by other users there has been no official comment or action on it yet.

Could one of the maintainers of APCU attest in the bug report that replacing 4.0.2 qualifies as a critical update? https://bugs.launchpad.net/ubuntu/+source/php-apcu/+bug/1374892

**Comment by krakjoe** [comment]
I done that, sorry it took so long ...

**Comment by themightychris** [comment]
Hey @krakjoe could you comment on the latest in that thread on what the best release to ship would be according to their standards?

**Comment by krakjoe** [comment]
I am unsure of their standards, I don't use LTS anything.

Below 4.0.10 there is a serious flaw in ACPu that makes it unstable.

If they ship anything below that version, they are going to make users lives difficult.
