### ISSUE TITLE
apcu status page not working

### ISSUE THREAD

**Issue by pumpkintits** [krakjoe/apcu#109]
I have w3 total cache enabled and using apcu, and it's greatly sped up the webpage, however the apcu.php status page does not show the website is utilizing any cache at all, hits and misses are both 0.0%. I am running php-fpm, nginx, Amazon Linux, php 5.5.21, APCu 4.0.4, and the apc.php page found on this page I'm commenting on.

**Comment by web-candy** [comment]
Same for me, I used the current apc.php and "Cache Information" in the "View Host Stats" view are empty. Also, the "User Cache Entries" view does just show one unnamed entry, even though there should be more, see http://i.imgur.com/kNnhYQt.png.
A quick test revealed that apc_add() and apc_fetch() work:

var_dump(apc_add('test1', 'a_string')); // bool(true) 
var_dump(apc_fetch('test1')); // string(8) "a_string"

**Comment by jbenoit2011** [comment]
I got the same problem and resolved it by upgrading APCu to the latest version (4.0.7 in my case)

**Comment by krakjoe** [comment]
This has been fixed.
