### ISSUE TITLE
Is APCu stable or beta?

### ISSUE THREAD

**Issue by slavafomin** [krakjoe/apcu#110]
Hello!

I was looking into this package in order to implement caching in my Symfony 2 application.

However, I'm bit confused, is this package considered **STABLE** and ready to use in production or is it **BETA**?

The Git repository has a valid stable version tags, but PECL website states, that this package is beta:
http://pecl.php.net/package/APCu

Could you elaborate please?

Thank you!

**Comment by krakjoe** [comment]
APCu was forked from a beta version of APC.

The beta stuff in APC would have been mostly to do with the current version of PHP, it would have been opcode related stuff.

APCu could have been called stable, but decided to mark as beta in pecl to be on the safe side. The plan was to mark stable after a few releases, but there has been a few unconfirmed reports of instability, so I stalled further.

The API is stable, I can't really change it if I want to stay compatible with APC. For the most part APCu should be considered stable, I think.

I will do something about pecl status on the next release.

**Comment by mishan** [comment]
@slavafomin @krakjoe I work for Ifwe, the company that owns Tagged.com and we serve millions of users. We've been using PHP 5.6 + Zend OpCache + APCu since last fall successfully. APCu appears to work flawlessly.

**Comment by slavafomin** [comment]
Thank you @krakjoe and @mishan! You've completely relieved my concerns = )
