### ISSUE TITLE
Strange decoding problem

### ISSUE THREAD

**Issue by cmodijk** [krakjoe/apcu#111]
We currently have an issue where decoding data from apcu has some strange behavior the following should be a array with strings as keys and values but it look's like this:

![decoding](https://cloud.githubusercontent.com/assets/771041/6712785/ca77fcc4-cd8e-11e4-892e-800f1703b6f8.png)

We are using Doctrine2 and Doctrine APC caching.

Server: CentOS 6.5
PHP Version: 5.6.6
APCu Version: 4.0.7

**Comment by thestanislav** [comment]
See this https://github.com/krakjoe/apcu/issues/38

**Comment by cmodijk** [comment]
@thestanislav tnx
