### ISSUE TITLE
Broken, or install instructions incomplete

### ISSUE THREAD

**Issue by teo1978** [krakjoe/apcu#114]
I've tried installing both with ```apt-get install php5-apcu``` and with ```pecl install apcu``` and both installations appeared to be succesful.
I had to manually copy apcu.so to the correct path for php extensions.
I added ```extension=apcu.so``` in php.ini and restarted apache, but the extension is still not loading, as if non-existent.
It doesn't show up in phpinfo(), and extension_loaded() returns false.
This is on php 5.4.29 on Debian

**Comment by tedivm** [comment]
For the record I'm having this exact same issue on the Travis-CI machines, but on my home machine it is fine.

**Comment by krakjoe** [comment]
This is not a bug, this is a server admin issue, might I suggest Serverfault/Stackoverflow.

**Comment by teo1978** [comment]
How is it not a bug ifbyou install a package following its installation instructions and it doesn't work out of the box?

If you need to ask on ServerFault to figure out how to  get it working, either the distributed package is broken or documentation is incomplete

**Comment by teo1978** [comment]
By the way, if I remember correctly, it turned out to be the php5-apcu Debian package to be broken. After installing the pecl package with pecl, the lib from previously installed Debian package was still meeting used. I uninstalled everything and reinstalled with pecl and it worked.

So, it's not a "server admin issue", it's the package for Debian  that is broken.

Either fix it, or drop it, so users won't waste time with it and will go directly to the installation method that works.

**Comment by kelunik** [comment]
That's still not a bug here, report it to the Debian package maintainers.
