### ISSUE TITLE
debian package is broken

### ISSUE THREAD

**Issue by teo1978** [krakjoe/apcu#115]
I don't know who maintains the debian package php5-apcu, but it's broken.

I installed it via  ```apt-get php5-apcu``` and it didn't work (details below).
On the other hand, installing it via ```pecl install channel://pecl.php.net/apcu-4.0.7``` worked.

Here are the details just in case you don't trust a generic "didn't work".

1) I ran:
   apt-get install php5-apcu
2) I copied the file apcu.so that was installed in a random directory to the correct directory for PHP extensions
3) I added this to php.ini:
  extension=apcu.so
4) I restarted apache, and tested by requesting from a browser a PHP script that calls phpinfo()
5) I ran "php -m"

Expected behavior:
apcu should work

Observed:
4 - phpinfo() (called via web) would show nothing about apcu
5 - "php -m" from the CLI showed an error message, more or less like
  "apcu: cannot initialize module" (or "extension", don't remember exactly)

So I uninstalled it (apt-get remove), and I installed it with pecl:
  pecl install channel://pecl.php.net/apcu-4.0.7
I repeated steps 2-5 and this time it worked like a charm.

**Comment by krakjoe** [comment]
Closing, because housework, I'm not the maintainer of the debian package, I don't know who is either.
