### ISSUE TITLE
Modification time key incompatible with APC

### ISSUE THREAD

**Issue by ptdev** [krakjoe/apcu#117]
Hello, on APC, the key name for the modification name was "mtime" and on APCu, this seems to have been changed to "modification_time".
A lot of third party libraries and frameworks that support APC use this value and so it's causing errors since it cannot find the key.
That being said, I agree that "modification_time" seems to be more consistent with the rest of the variables but unfortunately that breaks backwards compatibility.
Will this be changed in a future version to match the APC values (or maybe supply both keys for a while) or should we update any APC aware code to always use the new key and forget the old one?

**Comment by Stricted** [comment]
see https://github.com/krakjoe/apcu/pull/107

**Comment by ptdev** [comment]
That's exactly it. Unfortunately, most people tend to just install apc from some package manager on their OS and most packages are built using the latest version available on PECL which is 4.0.7 that doesn't contain the fix.
That means special install/upgrade considerations are needed just for APCu, like patching or compiling it manually but that's pretty much unmanageable.
A better way I think would be to release a new version on PECL that is fully compatible with APC so most distros can have working apcu packages that don't break a lot of apc aware code.

**Comment by Stricted** [comment]
will be fixed in the next release
