### ISSUE TITLE
Undefined index: key in apc.php on line 1044

### ISSUE THREAD

**Issue by ache** [krakjoe/apcu#118]
It happens in this two lines. Is there a fix known?
***
$fieldkey='key';
...
echo '[\<a href="', $MY_SELF, '&OB=', $MYREQUEST['OB'], '&DU=', urlencode($entry[$fieldkey]), '">Delete Now\</a>]'; 
***

**Comment by jensk** [comment]
Rename 'key' to 'info"

**Comment by ache** [comment]
Thanx, it works! Why this change is not committed yet to current apc.php?

**Comment by EAnushan** [comment]
Ran into the same warning with PHP warnings turned on. The rename from "key" to "info" worked. Can we get this committed so it can be packaged by the various distros?

**Comment by Xenopathic** [comment]
This was changed in #42, which was merged quite a while ago...
