### ISSUE TITLE
apc.shm_size has no effect to seg_size?

### ISSUE THREAD

**Issue by kayue** [krakjoe/apcu#132]
No matter what value I set to `apc.shm_size` in php-fpm, the `apc_sma_info()['seg_size']` always equal to `33554296`, is it normal?

I want to allocate more memory to APCu.

**Comment by kayue** [comment]
Please see attached.

![apcu_info__ip-10-0-1-22___10_0_1_22_](https://cloud.githubusercontent.com/assets/193112/10305577/80e140c0-6c53-11e5-9f05-f67b5955f3d8.png)

**Comment by krakjoe** [comment]
You have only allowed one segment, your OS is limiting the size of segments to ~32M and your settings prohibit splitting the storage across more than one segment.
