### ISSUE TITLE
Is there an ETA for a stable pecl release of the extension ?

### ISSUE THREAD

**Issue by stof** [krakjoe/apcu#134]

**Comment by krakjoe** [comment]
Hopefully in time for the first stable release of PHP7, there is still a little more work to do ...

**Comment by krakjoe** [comment]
Now, we should be good.

**Comment by neo22s** [comment]
Congrats on the first release! but how do we install it? the instructions are not updated, https://github.com/krakjoe/apcu/blob/master/INSTALL or just follow same procedure? thanks!
