### ISSUE TITLE
Working with apcu in CLI

### ISSUE THREAD

**Issue by gephaest** [krakjoe/apcu#136]
Hi. I had tested acpu with php-fpm and it works fine. But I need possibility to cache data in my CLI scripts.
I added to my config
```
apc.enabled=1
apc.enable_cli=1
```
and tried execute in CLI:
```php
<?php
apc_store('key', 'foo');
var_dump(apc_fetch('key')); // prints foo
```
Next, I commented first row and apc_fetch returns ``false``.
Is it possible to store and fetch data in cache between script executions?

**Comment by krakjoe** [comment]
>  Is it possible to store and fetch data in cache between script executions?

Not with APC.

**Comment by Dibbyo456** [comment]
@krakjoe So in cli apcu stored data is destroyed when execution end?
