### ISSUE TITLE
apc_exists() allways returns false for array of keys (PHP 7)

### ISSUE THREAD

**Issue by iotch** [krakjoe/apcu#141]
Hello.
According to [docs] (http://php.net/manual/en/function.apc-exists.php) `apc_exists()` should accept array of keys and return an assoc array of key => bolean pairs. However now it returns `false` with an array as argument (apcu 5.0.0-dev, PHP 7.0.0RC6).
Example:
````php
apc_store('a', 1);
$exists = apc_exists(['a']);
````
`$exists` expected to be an array, but `false` returned.

What s the correct behavior of `apc_exists()`?
Thanks.

**Comment by remicollet** [comment]
I don't reproduce

     php  -d apc.enable_cli=1 -r 'var_dump(apc_store("foo", 1), apc_fetch("foo"), apc_exists("foo"), apc_exists(["foo"]));'
     bool(true)
     int(1)
     bool(true)
     array(1) {
       ["foo"]=>
       bool(true)
     }

**Comment by iotch** [comment]
@remicollet have you tried with apcu 5.0.0-dev and PHP 7.0.0RC6?

**Comment by remicollet** [comment]
you're right, broken with 7.0.0

**Comment by remicollet** [comment]
I have the fix, will commit soon (after having the test)

**Comment by remicollet** [comment]
@iotch can you please test ?

**Comment by iotch** [comment]
@remicollet I've updated from your repo and it seems it woks as expected now. Thank you!

**Comment by remicollet** [comment]
Nice :)
Thanks for the test.
