### ISSUE TITLE
Endless loop with APCu in BC layer (PHP 7)

### ISSUE THREAD

**Issue by LionsAd** [krakjoe/apcu#146]
Happens for me with Drupal 8 and core/rebuild.php - Details will follow. 

Seems to be related to an apc_fetch call that leads in Drupal to an endless loop.

It works if I switch over all calls to use apcu_* functions instead curiously ... (and if I don't load apc.so)

**Comment by krakjoe** [comment]
Any more details available yet ?

**Comment by LionsAd** [comment]
Yes, so:

- It happens when I enable apc.so in php.ini in addition to apcu.so.
- It seems to be related to the serializer.

When I serialize the objects manually to strings before they enter the cache, then it works properly.

I still cannot see where the endless loop is as the objects returned look 'okay', but maybe serializer rings a bell.

**Comment by krakjoe** [comment]
Try setting apc.serializer=php in configuration, see if that affects it ?

**Comment by krakjoe** [comment]
Since this has been separated to apcu-bc, please upgrade and reopen on that repo if still occurring ...

Thanks ;)
