### ISSUE TITLE
TS builds for PHP7 on Windows broken

### ISSUE THREAD

**Issue by Jan-E** [krakjoe/apcu#150]
Hi @krakjoe 

The TS builds for PHP 7 on Windows are broken. See http://windows.php.net/downloads/pecl/releases/apcu/5.1.0/logs/php_apcu-5.1.0-7.0-ts-vc14-x64-logs.zip

	apc_cache.obj : error LNK2001: unresolved external symbol _tsrm_ls_cache
	C:\obj\7.0-ts-windows-vc14-x64\Release_TS\php_apcu.dll : fatal error LNK1120: 1 unresolved externals

Solution: change the line in config.w32 from

	EXTENSION('apcu', apc_sources);

into

	EXTENSION('apcu', apc_sources, PHP_APCU_SHARED, "/DZEND_ENABLE_STATIC_TSRMLS_CACHE=1");

**Comment by krakjoe** [comment]
I have repackaged and retagged 5.1.0, hopefully the windows build system will pick up the change ...

Thanks :)

**Comment by krakjoe** [comment]
Should be fixed for 5.1.1

**Comment by fabicz** [comment]
Can we look into recent build issues with 5.1.1/5.1.2 for PHP7?

```Unknown option --enable-apc-bc; please try configure.js --help for a list of valid options```
