### ISSUE TITLE
PHP 7 + apcu missing APC support emulated

### ISSUE THREAD

**Issue by layanto** [krakjoe/apcu#151]
Not sure if incorrect configuration on my part, but with PHP 7 x64 and apcu 5.1.0 on Windows, I don't see APC support emulated in PHPinfo(). I am using the same configuration as with PHP 5.6 x86 and apcu 4.08 (which has APC support emulated). Is the APC support emulated removed in apcu 5.1.0?

**Comment by Stricted** [comment]
https://github.com/krakjoe/apcu/issues/137#issuecomment-150760383

**Comment by layanto** [comment]
Thank you but I am on Windows using php_apcu.dll from http://windows.php.net/downloads/pecl/releases/apcu
There is no php_apc.dll to load after loading php_apcu.dll. I think apcu.so and apc.so is for Linux?

**Comment by krakjoe** [comment]
It seems the windows build system is not packaging ```apc.so``` ...

@weltling please can we get this adjusted ? Also can we get 5.1.1 removed because release was retracted and it won't build the release when I do it again ...

**Comment by remicollet** [comment]
@krakjoe perhaps we have to fix config.m4/w32 to have BC extension build by default ?

**Comment by krakjoe** [comment]
Ah, config.w32 is missing apc.so related stuff actually ...

**Comment by krakjoe** [comment]
Last commit should have fixed it, untested because my windows vm is not booting ... installing updates in a loop ...

@Jan-E would you have the time to test that for me please ?

I'll install a VM, but it takes a million years to install MSVC ...

**Comment by Jan-E** [comment]
Does not work. With

	EXTENSION(apc, "bc/php_apc.c", PHP_APCU_SHARED, "/DZEND_ENABLE_STATIC_TSRMLS_CACHE=1");

I get

	C:\php-sdk\php70dev\configure.js(4476, 3) Microsoft JScript runtime error: 'apc' is undefined

And with

	EXTENSION('apc', "bc/php_apc.c", PHP_APCU_SHARED, "/DZEND_ENABLE_STATIC_TSRMLS_CACHE=1");

.

	C:\php-sdk\php70dev\configure.js(4489, 5) Microsoft JScript runtime error: 'PHP_APC_BC' is undefined

Further testing will be late this evening.

**Comment by krakjoe** [comment]
Woops, that should be better ?

**Comment by Jan-E** [comment]
It still had the "epc is not defined" error. There is  a chance that this will do the trick:
https://github.com/Jan-E/apcu/blob/master/config.w32

It builds php_apc.dll besides php_apcu.dll, but you cannot load them both. If you try to do that Windows complains that module apcu is already loaded.

But maybe that is not needed, because of:
https://github.com/Jan-E/apcu/blob/master/config.w32#L36

I had to add the sources to the 'apc' extension as well to get it compiled without errors. It leads to a lot 'multiple target' warnings for everything in apc_sources.

The resulting php_apc.dll is smaller that php_apcu.dll. php_apc.dll has all the sources except bc/php_apc.dll. php_apc.dll has only the apc_sources. I do not see any difference in the phpinfo() output.

Building all 4 versions right now.

**Comment by Jan-E** [comment]
New compilations available at https://www.apachelounge.com/viewtopic.php?t=6617

@layanto Are you using PHP7 x64 TS or NTS?

**Comment by layanto** [comment]
@jan-E I am using PHP7 x64 NTS

**Comment by marc-mabe** [comment]
Installing with `pecl` + `Enable full APC compatibility [yes]` I get the following: `configure: WARNING: unrecognized options: --enable-apc-bc` - see https://travis-ci.org/marc-mabe/zend-cache/jobs/93815232

**Comment by marc-mabe** [comment]
I'm not sure if this is related to this issue on windows but I found that in package.xml there is a `--enable-apc-bc` flag but in config.m4 it is called `--enable-apcu-bc`

**Comment by krakjoe** [comment]
That is related ...

I haven't managed to get a windows VM setup yet, my broadband has been dodgy all weekend and is now just plain down. I am tethered to mobile device ...

I will be looking myself, soon as I'm able to setup ... sorry about delay ...

**Comment by artyfarty** [comment]
Having same troubles building apcu for brewed php.

```
make clean
./configure --with-php-config=/usr/local/bin/php-config --enable-apcu --enable-apcu-bc
make && make install
php -r 'var_dump(function_exists("apc_fetch"));'
bool(false)

php -r 'var_dump(function_exists("apcu_fetch"));'
bool(true)
```

**Comment by krakjoe** [comment]
@artyfarty load apc.so module, it's separate from apcu.so because of php-src limitations ...

**Comment by krakjoe** [comment]
I got a windows VM working, but can't get it right ... drafted in expert help from @weltling ... he's super busy, so might be another bit of a wait ... but a fix is coming ...

**Comment by nicodmf** [comment]
The manual installation work, but I had the same problem than marc-mabe with pecl install on docker : 

             I'm not sure if this is related to this issue on windows but I found that in package.xml there is a --enable-apc-bc flag but in config.m4 it is called --enable-apcu-bc

**Comment by A-contresens** [comment]
I didn't manage to compile php 7 with the option --enable-apcu-bc (with the source code of apcu 5.1.0)
```
main/internal_functions_cli.c:85:2: error: 'phpext_apc_ptr' undeclared here (not in a function)
  phpext_apc_ptr,
  ^
Makefile:2076: recipe for target 'main/internal_functions_cli.lo' failed
make: *** [main/internal_functions_cli.lo] Error 1
```

If I delete the option  --enable-apcu-bc, I'm able to compile php and apcu is working.
But to make it works with symphony 2 I need the apc compatibility mode.

I tried to load th module apc.so but I didn't found it in my shared extensions folder.

**Comment by krakjoe** [comment]
We are still working on a windows compatible solution ... it looks like the compatibility module will have to be a separate pecl ext for windows ...

I'm waiting to see if @weltling can fix it any other way first ... sorry about the delay ...

**Comment by A-contresens** [comment]
Thank you @krakjoe no problem for the delay.

In fact, I'm on debian. My problem occurs when I tries to compile apcu statically into PHP with the option --enable-apcu-bc 

The dso compilation works perfectly.

**Comment by krakjoe** [comment]
Ah, I didn't get that ... I'll take a look at that ...

**Comment by krakjoe** [comment]
Okay, can you try again with the new setup ??

recursive clone this repo, or clone [apcu-bc](https://github.com/krakjoe/apcu-bc) and build and load separately  ...

I've tested on windows too ...

**Comment by A-contresens** [comment]
I've tested it on debian but I got this :

```
Forcing buildconf
Removing configure caches
rebuilding configure
rebuilding main/php_config.h.in
configure: WARNING: you should use --build, --host, --target
configure: WARNING: invalid host type: \
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking for a sed that does not truncate output... /bin/sed
checking build system type... Invalid configuration `\': machine `\' not recognized
configure: error: /bin/bash ./config.sub \ failed
```

**Comment by krakjoe** [comment]
no syntax errors in ```config.nice``` or ```config.*``` ?

**Comment by A-contresens** [comment]
I don't think so because if I removed --enable-apc, php is compiling fine

**Comment by A-contresens** [comment]
I don't think so because if I removed --enable-apc, php is compiling fine.

I cloned the new repo apcu-bc but I didn't manage to compile the module. There is no Makefile in the folder. How can I create the makefile to be able to compile it ?

**Comment by krakjoe** [comment]
Do this ... start again ...

    cd /path/to/php-src
    make distclean
    rm -rf ext/apcu
    rm -rf ext/apc
    rm -rf aclocal.m4
    git clone https://github.com/krakjoe/apcu ext/apcu
    git clone https://github.com/krakjoe/apcu-bc ext/apc
    ./buildconf --force
    ./config.nice
    make -j16
    sudo make install

replace ```-j16``` with whatever is appropriate for your system ...

**Comment by Jan-E** [comment]
Works on Windows:
https://phpdev.toolsforresearch.com/php-7.0.0-nts-Win32-VC14-x64.htm
https://phpdev.toolsforresearch.com/php-7.0.0-nts-Win32-VC14-x64.zip

Recompiling the other versions now.

**Comment by krakjoe** [comment]
We just got some tests together for apcu-bc @Jan-E, they were broken until a few minutes ago, might want to pull in those and run tests ?

Excellent stuff, thanks, as always :)

**Comment by A-contresens** [comment]
I start with a fresh vm and it is compiling. I think like you said I made a mistake in my ./configure option.

I test it on my server and the module is working fine.

Thank you very much for your support.

**Comment by Jan-E** [comment]
With x86 it fails:

    php_apc.obj : error LNK2001: unresolved external symbol _apc_iterator_ce
    C:\php-sdk\php70dev\Release\php_apc.dll : fatal error LNK1120: 1 unresolved externals
    NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\link.exe"' : return code '0x460'

**Comment by remicollet** [comment]
@Jan-E with ba021dba2b7ad23021612526c2f45903768606ab ?

**Comment by Jan-E** [comment]
Nope. Unedited output

 "cl.exe" /D COMPILE_DL_APCU /D APCU_EXPORTS=1 /DZEND_ENABLE_STATIC_TSRMLS_CACHE=1 /
nologo /I . /I main /I Zend /I TSRM /I ext /D _WINDOWS /D ZEND_WIN32=1 /D PHP_WIN32=1 /D WI
N32 /D _MBCS /W3 /FD /wd4996 /D_USE_32BIT_TIME_T=1 /guard:cf /MP /Zi /LD /MD /W3 /Ox /D NDe
bug /D NDEBUG /D ZEND_WIN32_FORCE_INLINE /GF /D ZEND_DEBUG=0 /I "C:\php-sdk\win32build\incl
ude" /D FD_SETSIZE=256 /I "..\zlib" /FoC:\php-sdk\php70dev\Release\ext\apcu\ /FpC:\php-sdk\
php70dev\Release\ext\apcu\ /FRC:\php-sdk\php70dev\Release\ext\apcu\ /FdC:\php-sdk\php70dev\
Release\ext\apcu\ /c ext\apcu\apc.c ext\apcu\apc_cache.c ext\apcu\apc_iterator.c ext\apcu\a
pc_lock.c ext\apcu\apc_mmap.c ext\apcu\apc_pool.c ext\apcu\apc_shm.c ext\apcu\apc_signal.c
ext\apcu\apc_sma.c ext\apcu\apc_stack.c ext\apcu\apc_windows_srwlock_kernel.c ext\apcu\php_
apc.c
apc.c
apc_cache.c
apc_iterator.c
apc_lock.c
ext\apcu\apc_cache.c(708): warning C4018: '<': signed/unsigned mismatch
ext\apcu\apc_cache.c(803): warning C4018: '<': signed/unsigned mismatch
ext\apcu\apc_cache.c(1228): warning C4146: unary minus operator applied to unsigned type, r
esult still unsigned
ext\apcu\apc_cache.c(1670): warning C4018: '<': signed/unsigned mismatch
apc_mmap.c
apc_pool.c
apc_shm.c
apc_signal.c
apc_sma.c
apc_stack.c
apc_windows_srwlock_kernel.c
ext\apcu\apc_sma.c(302): warning C4018: '<': signed/unsigned mismatch
ext\apcu\apc_sma.c(362): warning C4018: '<': signed/unsigned mismatch
ext\apcu\apc_sma.c(407): warning C4018: '<': signed/unsigned mismatch
ext\apcu\apc_sma.c(488): warning C4018: '<': signed/unsigned mismatch
ext\apcu\apc_sma.c(577): warning C4018: '<': signed/unsigned mismatch
ext\apcu\apc_sma.c(586): warning C4018: '<': signed/unsigned mismatch
ext\apcu\apc_sma.c(632): warning C4018: '<': signed/unsigned mismatch
ext\apcu\apc_sma.c(642): warning C4018: '<': signed/unsigned mismatch
php_apc.c
ext\apcu\php_apc.c(665): warning C4101: 'entry': unreferenced local variable
ext\apcu\php_apc.c(835): warning C4013: 'apc_iterator_delete' undefined; assuming extern re
turning int
Recreating build dirs
Recreating build dirs
Recreating build dirs
Recreating build dirs
libiconv_a.lib(iconv1.obj) : MSIL .netmodule or module compiled with /GL found; restarting
link with /LTCG; add /LTCG to the link command line to improve linker performance
   Creating library C:\php-sdk\php70dev\Release\php7.lib and object C:\php-sdk\php70dev\Rel
ease\php7.exp
Generating code
Finished generating code
   Creating library C:\php-sdk\php70dev\Release\php_apcu.lib and object C:\php-sdk\php70dev
\Release\php_apcu.exp
EXT apcu build complete

C:\php-sdk\php70dev>nmake php_apc.dll

Microsoft (R) Program Maintenance Utility Version 14.00.23026.0
Copyright (C) Microsoft Corporation.  All rights reserved.

Recreating build dirs
Recreating build dirs
Recreating build dirs
Recreating build dirs
libiconv_a.lib(iconv1.obj) : MSIL .netmodule or module compiled with /GL found; restarting
link with /LTCG; add /LTCG to the link command line to improve linker performance
   Creating library C:\php-sdk\php70dev\Release\php7.lib and object C:\php-sdk\php70dev\Rel
ease\php7.exp
Generating code
Finished generating code
   Creating library C:\php-sdk\php70dev\Release\php_apcu.lib and object C:\php-sdk\php70dev
\Release\php_apcu.exp
        "cl.exe" /D APC_DEBUG=1 /D WIN32_ONLY_COMPILER=1 /D COMPILE_DL_APC /D APC_EXPORTS=1
 /DZEND_ENABLE_STATIC_TSRMLS_CACHE=1 /nologo /I . /I main /I Zend /I TSRM /I ext /D _WINDOW
S /D ZEND_WIN32=1 /D PHP_WIN32=1 /D WIN32 /D _MBCS /W3 /FD /wd4996 /D_USE_32BIT_TIME_T=1 /g
uard:cf /MP /Zi /LD /MD /W3 /Ox /D NDebug /D NDEBUG /D ZEND_WIN32_FORCE_INLINE /GF /D ZEND_
DEBUG=0 /I "C:\php-sdk\win32build\include" /D FD_SETSIZE=256 /I "..\zlib" /FoC:\php-sdk\php
70dev\Release\ext\apcu-bc\ /FpC:\php-sdk\php70dev\Release\ext\apcu-bc\ /FRC:\php-sdk\php70d
ev\Release\ext\apcu-bc\ /FdC:\php-sdk\php70dev\Release\ext\apcu-bc\ /c ext\apcu-bc\php_apc.
c
php_apc.c
   Creating library C:\php-sdk\php70dev\Release\php_apc.lib and object C:\php-sdk\php70dev\
Release\php_apc.exp
php_apc.obj : error LNK2001: unresolved external symbol _apc_iterator_ce
C:\php-sdk\php70dev\Release\php_apc.dll : fatal error LNK1120: 1 unresolved externals
NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\lin
k.exe"' : return code '0x460'
Stop.

**Comment by Jan-E** [comment]
> @Jan-E with  https://github.com/krakjoe/apcu/commit/ba021dba2b7ad23021612526c2f45903768606ab  ?

It has some effect: now the x64 build lacks BC as well...

**Comment by Jan-E** [comment]
I reverted https://github.com/krakjoe/apcu/commit/ba021dba2b7ad23021612526c2f45903768606ab and analyzed php_apcu.lib. This might give you a clue:

    C:\php-sdk\php70dev\x64\Release>dumpbin /exports php_apcu.lib | grep iterator
                  apc_iterator_ce
                  apc_iterator_init
                  apc_iterator_obj_init

    C:\php-sdk\php70dev\x64\Release>cd \php-sdk\php70dev\release

    C:\php-sdk\php70dev\Release>dumpbin /exports php_apcu.lib | grep iterator
                  _apc_iterator_ce
                  _apc_iterator_init
                  _apc_iterator_obj_init

The same difference applies to all other extensions:

    C:\php-sdk\php70dev\x64\Release>dumpbin /exports php_raphf.lib | grep acquire
                  php_persistent_handle_acquire

    C:\php-sdk\php70dev\x64\Release>cd \php-sdk\php70dev\release

    C:\php-sdk\php70dev\Release>dumpbin /exports php_raphf.lib | grep acquire
                  _php_persistent_handle_acquire

**Comment by Jan-E** [comment]
Functions that need to be used by other extensions:

    C:\php-sdk\php70dev\Release>cd \php-sdk\php70dev\release

    C:\php-sdk\php70dev\Release>dumpbin /exports php_apcu.lib | grep serial
                  __apc_register_serializer
                  _apc_cache_serializer
                  _apc_find_serializer
                  _apc_get_serializers
                  _php_apc_serializer
                  _php_apc_unserializer

    C:\php-sdk\php70dev\Release>dumpbin /exports php_igbinary.lib | grep serial
                  _igbinary_serialize
                  _igbinary_serialize_ex
                  _igbinary_unserialize

    C:\php-sdk\php70dev\Release>cd \php-sdk\php70dev\x64\release

    C:\php-sdk\php70dev\x64\Release>dumpbin /exports php_apcu.lib | grep serial
                  _apc_register_serializer
                  apc_cache_serializer
                  apc_find_serializer
                  apc_get_serializers
                  php_apc_serializer
                  php_apc_unserializer

    C:\php-sdk\php70dev\x64\Release>dumpbin /exports php_igbinary.lib | grep serial
                  igbinary_serialize
                  igbinary_serialize_ex
                  igbinary_unserialize

**Comment by Jan-E** [comment]
Solved it for x86 (and x64) with https://github.com/krakjoe/apcu-bc/pull/2

**Comment by krakjoe** [comment]
Excellent, closing issue ... pecl is coming for bc layer ...

**Comment by Jan-E** [comment]
BTW: phpinfo is showing version 0.0.0 now for BC ;)

**Comment by krakjoe** [comment]
Yeah, there is an open issue RE versions ... will be fixed before first release ;)

**Comment by layanto** [comment]
Is the intention to support BC indefinitely? Or is BC to be deprecated? If to be deprecated maybe should have the BC log in PHP everytime apc_* function is called. This way can track which code is using the BC functions and can change them to use the apcu_* equivalent.

**Comment by redstrike** [comment]
This issue still happens now. I am using **Windows 10 Pro x64**, the latest version of Uniform Server ZeroXII, **PHP 7.0.8**. And I've downloaded the **Thread Safe version** at https://pecl.php.net/package/APCu/5.1.5/windows

APCu doesn't show up in phpinfo().

**Comment by Wirone** [comment]
**INFO**: I had [`php_apcu-5.1.8-7.1-ts-vc14-x86.dll`](http://windows.php.net/downloads/pecl/releases/apcu/) and [`php_apcu_bc-1.0.3-7.1-ts-vc14-x86.dll`](https://pecl.php.net/package/apcu_bc/1.0.3/windows) but XAMPP, when starting server, printed error about missing `php_apcu.dll`. I've created symlink `php_apcu.dll -> php_apcu-5.1.8-7.1-ts-vc14-x86.dll` but error still was shown. I had to **rename** dll to `php_apcu.dll` and use it in `php.ini` under this exact name.
