### ISSUE TITLE
Compatibility not enable with the last pecl version 5.1.2

### ISSUE THREAD

**Issue by jordiferte** [krakjoe/apcu#154]
With the command : pecl install apcu-5.1.2, I have just that : 

![capture du 2015-12-07 16 21 35](https://cloud.githubusercontent.com/assets/10268516/11630597/a8847d0a-9cfe-11e5-9a22-7846ecc1e183.png)

No apc.so present, even if I selected the bc option in the pecl installation process.

Did I forget anything ?

Thank you for your development.

Best regards.

**Comment by remicollet** [comment]
pecl install apcu-bc

**Comment by brettpappas** [comment]
I think it should be:
pecl install apcu_bc
or
pecl install apcu_bc-beta

**Comment by krakjoe** [comment]
Yeah, it's apcu_bc on pecl, you can't have hyphens ... beta too ...
