### ISSUE TITLE
APCU 5.1.2 builds on Windows broken

### ISSUE THREAD

**Issue by fabicz** [krakjoe/apcu#156]
There still seems to be issue or misconfiguration of build for Windows for new APCU 5.x. Can you please check? PHP7 is now official and there is no proper build for it for TS. Only non-TS 5.1.0.

http://windows.php.net/downloads/pecl/releases/apcu/5.1.2/

**Comment by krakjoe** [comment]
You do need to use 5.1.2, the previous versions have known flaws ...

I am aware it's broken, @weltling is our windows man and as RM for 7 he is extremely busy ... 

As it's only the pecl build that is broken, not the build or extension, @Jan-E might be kind enough to provide you a build if you provide your required architecture ...

Failing that, a little wait ... sorry about that ...

**Comment by fabicz** [comment]
That would be lovely, we would like to do some initial tests. I'm looking particularly for php_apcu-5.1.2-7.0-ts-vc14-x64.dll then.

**Comment by Jan-E** [comment]
Check https://www.apachelounge.com/viewtopic.php?t=6359
https://phpdev.toolsforresearch.com/php-7.0.0-Win32-VC14-x64.htm

**Comment by fabicz** [comment]
Thanks, was helpful
