### ISSUE TITLE
Can it support php7-win32-x64 as .dll extension?

### ISSUE THREAD

**Issue by angusfenying** [krakjoe/apcu#157]
I got the sources, and turned it into VC2015 project.

yet, it lacks a line to include `zend_smart_str.h` in `php_apc.h`, just add a line:
```
#include "zend_smart_str.h"
```

Now it's compiled successfully, but, the php7 can't not recognize it, with following info displaying.
```
PHP Warning:  PHP Startup:  in Unknown on line 0
<br />
<b>Warning</b>:  PHP Startup:  in <b>Unknown</b> on line <b>0</b><br />
```

Maybe it's due to the version of VS2015 I am using? I'm using VS2015 Community(update 1).

**Comment by weltling** [comment]
Visual Studio can be used without any issues. What you need are the correct project settings. Also the latest master builds fine without any corrections.

In PHP we usually don't use Visual Studio but makefiles. What could probably do the best job, if you need a VS project, is first build APCu the usual way using nmake, and then generate a VS project from the PDB file.

Thanks.

**Comment by angusfenying** [comment]
Unbelievable, I can compile and use __yaconf__, or other extensions, before I updated the VS2015 to update 1 version. Now I reinstalled VS but the extensions still couldn't work.
