### ISSUE TITLE
apc_inc() with negative step value hangs the PHP 7 process

### ISSUE THREAD

**Issue by pierres** [krakjoe/apcu#158]
Calling apcu_inc() with a negative step value hangs the entire process. This used to work PHP 5.6.

Steps to repdoruce:
* Configure apcu on PHP 7 with apc.enable_cli=1
* Run php -a and try:

  php > apcu_inc('a', -1);

**Comment by krakjoe** [comment]
So that values in the cache overflow consistently with zend, we decided to use the API functions for increment and decrement, this breaks the logic when you use a negative value...

@remicollet @weltling I prefer throwing an exception when a negative value is used with apc_inc (since you should be using apc_dec), what do you think ?

**Comment by weltling** [comment]
I'd be in general ok with Exceptions. We're not in the core here, so to decide this were much easier. 

What i'd mention is that there's the third `&$success` argument documented for this function which allows to retain the usual PHP behavior. For predictability i'd rather suggest to schedule Exceptions for the next major, while  also checking which other functions could be switched. Probably were cool if the core would switch to having exceptions in functions at about same stage, but not obligatory.

Thanks.

**Comment by krakjoe** [comment]
That commit should make it behave like APC, can we check it please ?

**Comment by krakjoe** [comment]
Should be better, can we test that (compare with old APC), make sure nothing is strange ?

**Comment by staabm** [comment]
@krakjoe maybe it would make sense to run the apcu testsuite against apc and apcu and compare the results of both (maybe even continuous)?

**Comment by krakjoe** [comment]
I have compared the results, I run both versions still, but there wasn't tests that dealt with this particular use case ... and guess some folks have real world use cases ... they are free to submit tests ... or I'll put one together before release ...

**Comment by remicollet** [comment]
@krakjoe see 06584e154d8391483a6f4a81d52b746c0f484eaa

**Comment by remicollet** [comment]
Should be fixed,
More change committed, Test of master welcome.

**Comment by pierres** [comment]
I have built and tested the master branch and it fixes the problem. Thanks a lot!

**Comment by remicollet** [comment]
Thanks for the test.
