### ISSUE TITLE
Release of 5.1.2 broke pecl install for PHP 5.x

### ISSUE THREAD

**Issue by teohhanhui** [krakjoe/apcu#159]
`pecl install apcu` errors out because it's trying to install `5.1.2` instead of `4.0.10`

For example: https://travis-ci.org/Atlantic18/DoctrineExtensions/jobs/97188669

**Comment by remicollet** [comment]
This is not a apcu issue, but a pear/pecl one.

"pecl" command is unable to manage minimun version (which is part of the package metadata)
while this work for "pear" this will imply a change in the pecl rest interface.

**Comment by teohhanhui** [comment]
But this still breaks many existing Travis builds, and who knows how many other deployments...

**Comment by remicollet** [comment]
I understand, but not something we can fix in APCU side
Please report this on https://pear.php.net/bugs/report.php?package=PEAR

**Comment by remicollet** [comment]
Notice: apcu is not the only project which is affected:

    pecl.php.net Available Upgrades (stable):
    =========================================
    Channel      Package Local           Remote              Size
    pecl.php.net APCu    4.0.10 (stable) 5.1.2 (stable)      106kB
    pecl.php.net msgpack 0.5.7 (beta)    2.0.0 (beta)        45kB
    pecl.php.net pq      1.0.0RC1 (beta) 2.0.0RC1 (beta)     63kB
    pecl.php.net propro  1.0.2RC1 (beta) 2.0.0RC1 (beta)     13.1kB
    pecl.php.net raphf   1.1.1RC1 (beta) 2.0.0RC1 (beta)     15.4kB
    pecl.php.net rrd     1.1.3 (stable)  2.0.0beta2 (stable) 18.8kB
    pecl.php.net yac     0.9.2 (beta)    2.0.0 (beta)        32kB

**Comment by neclimdul** [comment]
Found a relevant [issue](https://pear.php.net/bugs/bug.php?id=21008) for googlers ending up here.

Does anyone have any suggestions on "targeting" a version, something like 4.x? or do we just have to type 4.0.10 and watch the apcu pecl page for releases for now?

**Comment by teohhanhui** [comment]
And then now with the release of 4.0.11 it has just broke every `pecl install apcu` for folks using PHP 7... Great!

**Comment by remicollet** [comment]
Again, don't complain here => https://github.com/pear/pear-core
