### ISSUE TITLE
Why apcu_* funcs but APC_* const and apc.* ini entries?

### ISSUE THREAD

**Issue by nicolas-grekas** [krakjoe/apcu#162]
This looks inconsistent, isn't it? What's the reason for that?

**Comment by remicollet** [comment]
To avoid breaking configuration after update...
I don't see simple way to rename those options...

**Comment by nicolas-grekas** [comment]
For the constants, you should provide both names as plan to drop the APC_* names in the future,
for the ini settings, you could accept both, and maybe log a startup notice when apc_* settings are used?
An other alternative is to revert the push for the `u` and get back to `apc_*` functions/classes, this has a less pain effort for everyone. But I guess it's too late now :(
And of course the statu quo may be the best option.
WDYT?

**Comment by krakjoe** [comment]
APC functions/classes are made available by the bc layer (submodule of this repo, apcu-bc ext).

We made the decision to keep configuration the same to ease the change from APC, to Opcache+APCu ... it's a decision that we cannot reverse.
