### ISSUE TITLE
Does apcu_delete support APCIterator?

### ISSUE THREAD

**Issue by JoyceBabu** [krakjoe/apcu#165]
According to http://php.net/manual/en/function.apc-delete.php#101794 `apcu_delete` accepts an instance of `APCIterator` as argument. But this is not working for me. Is this a supported feature, or am I doing it wrong?

Edit: Sorry, the sample code provided in the example is working. Let me re-check my code.

**Comment by remicollet** [comment]
This work and is test covered.
See => https://github.com/krakjoe/apcu/blob/master/tests/iterator_005.phpt

**Comment by JoyceBabu** [comment]
I am totally confused. If I iterate through the `APCIterator` before `apcu_delete`, then the entries are not getting deleted. Am I missing something?

    for ($i = 0; $i < 5; $i++) {
    	apcu_store("my_key_$i", $i);
    }
    
    $iter = new APCIterator('/^my_key_/', APC_ITER_VALUE);
    
    foreach ($iter as $val) {
    	// print_r($val);
    }
    var_dump( apcu_delete($iter) );
    
    $iter = new APCIterator('/^my_key_/', APC_ITER_VALUE);
    // This is not empty
    foreach ($iter as $val) {
    	print_r($val);
    }


But the following code is working as expected

    for ($i = 0; $i < 5; $i++) {
    	apcu_store("my_key_$i", $i);
    }
    
    $iter = new APCIterator('/^my_key_/', APC_ITER_VALUE);
    
    foreach ($iter as $val) {
    	// print_r($val);
    }
    
    $iter = new APCIterator('/^my_key_/', APC_ITER_VALUE);
    var_dump( apcu_delete($iter) );
    
    $iter = new APCIterator('/^my_key_/', APC_ITER_VALUE);
    // This is not empty
    foreach ($iter as $val) {
    	print_r($val);
    }

**Comment by vrga** [comment]
in the first case you have already iterated through the iterator's dataset in the foreach loop. remember, iterators !== arrays.

you can try $iter->rewind(); before passing it to apcu_delete, which should bring it back to its starting point.

according to the docs on [Iterator](http://php.net/manual/en/class.iterator.php), and particularily a [comment](http://php.net/manual/en/class.iterator.php#96691), foreach implicitly rewinds the iterator before starting to work on it. apcu_delete() obviously does not.

**Comment by JoyceBabu** [comment]
@vrga. Thank you for the clear explanation.
