### ISSUE TITLE
TTL issues

### ISSUE THREAD

**Issue by tgabi333** [krakjoe/apcu#167]
Can you approve that this is a bug:

```
php -r "var_dump(apc_store('hello', 'h', 2)); sleep(4); var_dump(apc_exists('hello')); var_dump(apc_fetch('hello'));"
```

outputs:
```
bool(true)
bool(true)
string(1) "h"
```

php 5.6.17 with APCU 4.0.7 and `apc.enable_cli=1`

**Comment by krakjoe** [comment]
This is symptomatic of default configuration where ```apc.use_request_time``` is enabled, this results in all APC API calls using the same timestamp, so expiry cannot be detected in a test scenario.

Simply disable ```apc.use_request_time``` in your test suite.

**Comment by tgabi333** [comment]
@krakjoe Thank you!

**Comment by tgabi333** [comment]
What is about the negative TTL?
I've still got false result for this:
```
php -r "var_dump(apc_store('hello', 'h', -1)); var_dump(apc_exists('hello')); var_dump(apc_fetch('hello'));"
```
outputs:
```
bool(true)
bool(true)
string(1) "h"
```
