### ISSUE TITLE
Improvement

### ISSUE THREAD

**Issue by faaliyet** [krakjoe/apcu#169]
http://php.net/manual/en/function.apcu-delete.php
Returns TRUE on success or FALSE on failure. 

What do you think about the idea;
TRUE: found and deleted.
NULL: not found
FALSE: failure

Because, I personally think, it should NOT (FAIL) return FALSE on successful command runs.

**Comment by faaliyet** [comment]
So, developers can know and handle failures instead of stateless results.

$result = apcu_delete('my_key');
```
if ($result === false) {
        throw new Exception('apcu_delete has failed. key: my_key ');
}
```
I don't know how does extension work internally, but I think, this improvement can be a good solution.

**Comment by krakjoe** [comment]
Changing the API means breaking billions of lines of code ... we can't do that.

**Comment by faaliyet** [comment]
so, it means wrong design will keep its status. well done.
notice for others, who want to have this feature, embedded databases can help with this.
