### ISSUE TITLE
Unserializable values leave a "null" state

### ISSUE THREAD

**Issue by nicolas-grekas** [krakjoe/apcu#170]
```php
try {
    apcu_clear_cache();
    apcu_store('foo', function(){});
} catch (\Exception $e) {
    var_dump(apcu_fetch(array('foo')));
}
```

currently displays `array(1) { ["foo"]=> NULL }`
but it should display `array(0) { }` instead.

**Comment by krakjoe** [comment]
This is consistent with how APC behaves, changing it, means breaking code ... we can't do that.

**Comment by staabm** [comment]
seems a fix for this was committed in https://github.com/krakjoe/apcu/commit/91d1ed4af16329063ed073072560dc794cd8ecb1

**Comment by krakjoe** [comment]
Yes, I changed my mind about that ... it's extremely wasteful and stupid to allow these entries to exist, and it creates much surprise ... it might break some code ... we have to move forward some time :)

**Comment by staabm** [comment]
@krakjoe your reasoning is totally find. I just wanted to let @nicolas-grekas know that it should be fixed now.

@krakjoe thx joe!
