### ISSUE TITLE
Problem with StartTime and hits

### ISSUE THREAD

**Issue by jekeyeke** [krakjoe/apcu#178]
Hi everyone,

I don't know why but the starttime is always in 1970 and hits 0. This is my configuration:

**General Cache Information**
APCu Version	4.0.8
PHP Version	5.5.25
Server Software	Apache/2.4.12 (Unix) PHP/5.5.25 OpenSSL/1.0.1e
Shared Memory	1 Segment(s) with 1024.0 MBytes
(mmap memory)
Start Time	1970/01/01 01:00:00
Uptime	46 years, 16 weeks, 5 days, 5 hours and 23 minutes
File Upload Support	1

**Cache Information**
Cached Variables	( 18.6 MBytes)
Hits
Misses
Request Rate (hits, misses)	0.00 cache requests/second
Hit Rate	0.00 cache requests/second
Miss Rate	0.00 cache requests/second
Insert Rate	0.00 cache requests/second
Cache full count	

But the strange is that ifia clear cache, the website will be slower than before (only the first time), so something is really caching.

Can anybody help me?

Thanks

P.D. I'm so sorry about my English

**Comment by remicollet** [comment]
I can't reproduce

    APCu Version	4.0.11
    Start Time	2016/04/27 06:25:36
    Hits	14
    Misses	4
    ...

**Comment by jekeyeke** [comment]
Thanks for the comment remicollet.

I updated to the last version and all works fine.


Bye
