### ISSUE TITLE
is there any way to dump a executable object file for fpm or cli ?

### ISSUE THREAD

**Issue by joostshao** [krakjoe/apcu#179]
is there any way to dump a executable object file for fpm or cli ?
i want to protect my code, and  run my project in a file, but not phar file.

i searched , but can not find some result. 
can you help me ? or give me some suggestion ?

**Comment by remicollet** [comment]
Various extension exists, phar, phk, blenc...

Closing as this is not related to APCu

**Comment by joostshao** [comment]
thank you all the same
