### ISSUE TITLE
4.0.11 compile fails with PHP 7.0.6

### ISSUE THREAD

**Issue by tvlooy** [krakjoe/apcu#180]
I didn't notice this with older versions but 4.0.11 does fail to compile with PHP 7.0.6. 

Example: https://gist.github.com/tvlooy/76093223b797d83987d5b47fb470e989

I don't have this problem with Git master, maybe time for a 4.0.12 release?

**Comment by remicollet** [comment]
4.0.x is only for PHP 5
5.1.x is only for PHP 7

**Comment by tvlooy** [comment]
@remicollet strange. Why doesn't it select the right version? I do a "pecl install apcu"

**Comment by remicollet** [comment]
pecl is not able to select the right version, according to running php.

Please file a bug on http://pear.php.net/package/PEAR

**Comment by tvlooy** [comment]
@remicollet I now understand that the reason why it did work with previous versions is because 4.0.11 has the newest release date and previously that was 5.1.3. I get it now
