### ISSUE TITLE
在MAC下，命令行多进程重复操作同一个key，会出现卡死不动

### ISSUE THREAD

**Issue by gufei** [krakjoe/apcu#181]
在MAC下，命令行多进程反复调用apcu_add(其他方法同样)同一个key
有时会报
Assertion failed: (NEXT_SBLOCK(NEXT_SBLOCK(cur))->prev_size == nxt->size), function sma_deallocate, file /Users/wujiaheng/Downloads/apcu-4.0.11/apc_sma.c, line 242.
然后卡死不动

有时不报错，直接卡死不动，求解
示例程序如下，反复执行，很容易出现
`
<?php

$p_num = 10;
$loopnum = 10;

function start(){
    $pid = pcntl_fork();
    if($pid>0)
    {
        return $pid;
    }
    elseif($pid==0)
    {
        worker();
    }
    else
    {
        echo "Error:fork fail\n";
    }
}

function worker(){

```
for($i=1;$i<=10;$i++){
    var_dump(apcu_add("100",1,0));
}
exit(0);
```

}

for($j=1;$j<=$p_num;$j++){
    $child_pid[] = start();
}

for($j=1;$j<=$p_num;$j++){
    $status = 0;
    $pid = pcntl_wait($status);
}

var_dump("ok");
`
MAC版本
`
  系统版本：   OS X 10.11.4 (15E65)
  内核版本：   Darwin 15.4.0
  启动宗卷：   Macintosh HD
  启动模式：   正常
  安全虚拟内存： 已启用
  系统完整性保护：  已启用
  启动后的时间长度：   8:23

  型号名称：   MacBook Pro
  型号标识符：    MacBookPro12,1
  处理器名称：    Intel Core i5
  处理器速度：    2.7 GHz
  处理器数目：    1
  核总数：  2
  L2 缓存（每个核）：   256 KB
  L3 缓存：  3 MB
  内存： 8 GB
  Boot ROM 版本：    MBP121.0167.B16
  SMC 版本（系统）： 2.28f7

`

PHP版本
`
PHP 5.5.34 (cli) (built: Apr 25 2016 18:07:45) (DEBUG)
Copyright (c) 1997-2015 The PHP Group
Zend Engine v2.5.0, Copyright (c) 1998-2015 Zend Technologies
    with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2015, by Zend Technologies
    with Xdebug v2.3.3, Copyright (c) 2002-2015, by Derick Rethans
`

我的ini配置如下
`
apc.enabled=1
apc.shm_size=256000000
apc.ttl=7200
apc.mmap_file_mask=/tmp/apc.XXXXXX
apc.enable_cli=1
apc.slam_defense=0 (改为其他值同样)
`
APC配置
`
apcu

APCu Support => Enabled
Version => 4.0.11
APCu Debugging => Disabled
MMAP Support => Enabled
MMAP File Mask => /tmp/apc.Rdaq4i
Serialization Support => php
Revision => $Revision: 328290 $
Build Date => May  6 2016 20:02:26

Directive => Local Value => Master Value
apc.coredump_unmap => Off => Off
apc.enable_cli => On => On
apc.enabled => On => On
apc.entries_hint => 4096 => 4096
apc.gc_ttl => 3600 => 3600
apc.mmap_file_mask => /tmp/apc.Rdaq4i => /tmp/apc.Rdaq4i
apc.preload_path => no value => no value
apc.rfc1867 => Off => Off
apc.rfc1867_freq => 0 => 0
apc.rfc1867_name => APC_UPLOAD_PROGRESS => APC_UPLOAD_PROGRESS
apc.rfc1867_prefix => upload_ => upload_
apc.rfc1867_ttl => 3600 => 3600
apc.serializer => php => php
apc.shm_segments => 1 => 1
apc.shm_size => 256000000 => 256000000
apc.slam_defense => Off => Off
apc.smart => 0 => 0
apc.ttl => 7200 => 7200
apc.use_request_time => On => On
apc.writable => /tmp => /tmp
`

**Comment by yyy2015c01** [comment]
这是github，用中文没人看得懂
