### ISSUE TITLE
x86 DLL for Windows

### ISSUE THREAD

**Issue by redstrike** [krakjoe/apcu#186]
I cannot use the x64 DLL provided, due to using **PHP 7.0.8 (x86)** that included with [**Uniform Server ZeroXII**](https://sourceforge.net/projects/miniserver/files/Uniform%20Server%20ZeroXII/).

Please included DLL for x86 like [**ext-redis**](https://pecl.php.net/package/redis/3.0.0/windows).

**Comment by krakjoe** [comment]
We don't do windows builds here.

http://windows.php.net/downloads/pecl/releases/apcu/
