### ISSUE TITLE
remove bc submodule

### ISSUE THREAD

**Issue by adambaratz** [krakjoe/apcu#187]
It looks like [f3c3b27dee39efb7cbe91d8a8db020720e38879f](https://github.com/krakjoe/apcu/commit/f3c3b27dee39efb7cbe91d8a8db020720e38879f) moved bc support to an external module, but there's still a bc submodule. Should it be removed so people don't use an older version of apc_bc by accident?

**Comment by krakjoe** [comment]
The git submodule is supposed to exist, it is the apcu-bc extension.
