### ISSUE TITLE
Segfault on PHP 7.1

### ISSUE THREAD

**Issue by nicolas-grekas** [krakjoe/apcu#188]
`composer self-update` crashes when apcu is enabled on php 7.1 (at least when done on travis-ci)

**Comment by remicollet** [comment]
Same issue, lot of segault (was ok with alpha1, broken with beta1)

```
Number of tests :   30                28
Tests skipped   :    2 (  6.7%) --------
Tests warned    :    0 (  0.0%) (  0.0%)
Tests failed    :   27 ( 90.0%) ( 96.4%)
Expected fail   :    0 (  0.0%) (  0.0%)
Tests passed    :    1 (  3.3%) (  3.6%)
```

**Comment by remicollet** [comment]
In fact this is not related to change in 7.1.0beta1, but to ZTS

TS-build, see previous
Non-TS build:
```
PHP         : /usr/bin/php 
PHP_SAPI    : cli
PHP_VERSION : 7.1.0beta1
ZEND_VERSION: 3.1.0-dev
=====================================================================
Tests passed    :   30 (100.0%) (100.0%)
```

**Comment by TysonAndre** [comment]
@remicollet Fixed in https://github.com/krakjoe/apcu/pull/192

See output of https://travis-ci.org/krakjoe/apcu/jobs/147086063 for php nightly.
