### ISSUE TITLE
expired cache is not removed after the ttl

### ISSUE THREAD

**Issue by omansour** [krakjoe/apcu#196]
Hey 

I am trying such a simple thing but it's not working and I cant figure why 

```php 
        apcu_clear_cache();

        apcu_store('test', 'raoul', 1);
        var_dump(apcu_fetch('test'));
        sleep(5);
        var_dump(apcu_fetch('test'));
```

should output something like : 

```
string(5) "raoul"
bool(false)
```

because the cache should expire during the sleep.

but I got 

```
string(5) "raoul"
string(5) "raoul"
```

any help will be very appreciated

**Comment by omansour** [comment]
I am using php 7.0.10 and apcu 5.1.5

**Comment by staabm** [comment]
Per docs ttl is defined as 

Time To Live; store var in the cache for ttl seconds. After the ttl has passed, the stored variable will be expunged from the cache (on the next request). If no ttl is supplied (or if the ttl is 0), the value will persist until it is removed from the cache manually, or otherwise fails to exist in the cache (clear, restart, etc.).

Soo. The variable will only be cleared in a later request

**Comment by omansour** [comment]
many thanks

**Comment by danielson317** [comment]
Sorry to re-open but "on the next request" is rather ambiguous and doesn't appear to be true. What operation will cause the value to be expunged? I tried:

```
  apcu_add('test1', 'test_value', 5);

  echo '<pre>';
  $tries = 0;
  do
  {
    echo $tries . ': ';
    if (apcu_add('test1', 'test_value'))
    {
      echo 'added' . "\n";
    }
    else
    {
      echo 'failed' . "\n";
    }
    sleep(1);
    $tries++;
  } while ($tries < 10);
  echo '</pre>';
```

The output is: 

```
0: failed
1: failed
2: failed
3: failed
4: failed
5: failed
6: failed
7: failed
8: failed
9: failed
```

`6` should have successfully added. If a new operation was required to activate the ttl then 7 should have added. TTL appears to be doing nothing.

**Comment by danielson317** [comment]
Found the issue and fixed.

For those who find this issue in the future using google. The issue with this script appears to be the configuration setting `apc.use_request_time=1`. This appears to say that the cache will never expire for a single thread as only the timestamp at the start of the thread is used not the actual request time. This is also the default behavior.

To fix place `apc.use_request_time=0` in your php.ini or `ini_set(apc.use_request_time, 0);` in your bootstrap file if you do not have access to php.ini file.

**Comment by JLuc** [comment]
In which release version is it now fixed ?
