### ISSUE TITLE
tag 5.1.6 ?

### ISSUE THREAD

**Issue by nicolas-grekas** [krakjoe/apcu#201]
Would be great, because 5.1.5 is segfaulting when running Symfony's test suite, but master in fine :)

**Comment by krakjoe** [comment]
Okay: @remicollet when you have time, please roll a release. Ta.

**Comment by remicollet** [comment]
I will do it tomorrow morning (now = time to disconnect and take some rest), so in ~10-12h

**Comment by krakjoe** [comment]
Thanks :)

**Comment by remicollet** [comment]
Released
