### ISSUE TITLE
can't support static compile~

### ISSUE THREAD

**Issue by paulgao** [krakjoe/apcu#202]
/root/php-5.6.26/ext/apcu/apc.c:41:31: fatal error: zend_smart_str.h: No such file or directory
 #   include "zend_smart_str.h"
                               ^
compilation terminated.
make: *** [ext/apcu/apc.lo] Error 1
make: *** Waiting for unfinished jobs....

plz check & fix it!

**Comment by krakjoe** [comment]
You are using the wrong version of apcu for PHP5, please check and fix it :)
