### ISSUE TITLE
Should (un)serialize all data types before apc_store/_fetch ?

### ISSUE THREAD

**Issue by axot** [krakjoe/apcu#210]
I found some frameworks like Zend framework will do serialize/unserialize before apc_store/apc_fetch. Is it necessary? I think it has performance impact, and igbinary will not work well too.

**Comment by krakjoe** [comment]
It is not necessary.

It may not have much of a performance impact, although the data will be serialized twice, a serialized string is not very expensive to construct.

Still, it doesn't really make sense to serialize in user land.
