### ISSUE TITLE
APCu Version Information

### ISSUE THREAD

**Issue by Nirjonadda** [krakjoe/apcu#211]
Hello,

APCu Version Check are not working. Unable to fetch version information. Please let me know that how to fixing on this issue?

Thanks

**Comment by kordianbruck** [comment]
Reading the code at https://github.com/krakjoe/apcu/blob/master/apc.php this should work just fine:
```
$apcversion = phpversion('apcu');
```

Works for me on my current server. Any more infos? Got a code snippet of what exactly you are trying to do?

**Comment by krakjoe** [comment]
No feedback, if there is a still a problem with the latest release, please open a new issue.
