### ISSUE TITLE
rfc1867 parameters

### ISSUE THREAD

**Issue by and0x000** [krakjoe/apcu#212]
I noticed, that there are some references on the rfc1867 upload hook both in the php.net documentation and in the "[INSTALL](https://github.com/krakjoe/apcu/blob/master/INSTALL)" file.

With major version 4 (according to [PECL versions](https://pecl.php.net/package/APCu)), it works as expected. 

With major version 5, the c-code for supporting any of these parameters seems to be missing and the parameters do not show up in a "phpinfo()" (on PHP 7.0.13, though I doubt that this info matters).

I could not find any commit messages, changelog or mailing list entry referencing the removal of this parameters.

**Comment by gapple** [comment]
It looks like [native upload progress handling](https://secure.php.net/manual/en/session.upload-progress.php) was added to PHP in 5.4.0.

Since APCu 5.1 requires PHP 7+, the native handling is probably preferred over APCu duplicating the same functionality.

**Comment by and0x000** [comment]
This may be a reasonable cause for the removal from APCu.
In this case however, there should imho be some annotation regarding the change in the documentation(s).

**Comment by alecpl** [comment]
Native upload handling has limitations. Please, reconsider.
