### ISSUE TITLE
Release 5.1.8 with fix for windows builds

### ISSUE THREAD

**Issue by TysonAndre** [krakjoe/apcu#213]
Visual studio wasn't able to parse the macros in 7.1. d6b1b431491ea312e9c093a5e6934d8f0401d424 fixes the macros. (see http://windows.php.net/downloads/pecl/releases/apcu/5.1.7/logs/)

Windows dlls are unavailable for https://pecl.php.net/package/APCu at the moment. I think it may (or may not) affect projects using apcu's headers, such as igbinary.

**Comment by krakjoe** [comment]
I thought the windows builds were fixed in place for the last release. I'll find out what happened there.

**Comment by weltling** [comment]
@krakjoe nope, usually not doing it. Can be done either that way, or i can trigger a current snapshot. Please let me know.

Thanks.

**Comment by krakjoe** [comment]
This was fixed in last release.
