### ISSUE TITLE
Empty (not deleteable) entries in apc.php

### ISSUE THREAD

**Issue by kordianbruck** [krakjoe/apcu#215]
So I'm not really sure, if I'm doing something wrong, but this is really weird:

![screenshot](https://cloud.githubusercontent.com/assets/298860/20501722/572eab46-b03b-11e6-94a7-249bbc87ebc1.png)

Guessing from the size, these entries seem to be like any other device entry. Somehow though they do not have a key, if I see this correctly. What exactly am I doing wrong?

I'm running php-fpm 7.0.13-1~dotdeb+8.1 with nginx 1.6.2 and APCu 5.1.7

Bonus: I'm getting segfaults in the php-fpm process from time to time, which might be related to this and is really annoying. (Might be related to #207) The log reads:
```
PHP Notice:  apcu_fetch(): Error at offset 832 of 964 bytes in ...
```

corresponding code line looks like this:
```
$data = apcu_fetch($id, $success);
```

Are these issues maybe related? Is it not wise to use entries without expiration?

**Comment by krakjoe** [comment]
This should have been fixed in the last release: please test and if the problem persists open a new issue.
