### ISSUE TITLE
Some errors when trying to compile 

### ISSUE THREAD

**Issue by nugroho08** [krakjoe/apcu#220]
Ah, I want to install APCu 5.1.7, when executing `make` here some errors :

`/bin/bash /home/ghost/apcu-5.1.7/apcu-5.1.7/libtool --mode=compile cc -D_GNU_SOURCE -DZEND_ENABLE_STATIC_TSRMLS_CACHE=1 -I. -I/home/ghost/apcu-5.1.7/apcu-5.1.7 -DPHP_ATOM_INC -I/home/ghost/apcu-5.1.7/apcu-5.1.7/include -I/home/ghost/apcu-5.1.7/apcu-5.1.7/main -I/home/ghost/apcu-5.1.7/apcu-5.1.7 -I/opt/lampp/include/php -I/opt/lampp/include/php/main -I/opt/lampp/include/php/TSRM -I/opt/lampp/include/php/Zend -I/opt/lampp/include/php/ext -I/opt/lampp/include/php/ext/date/lib  -DHAVE_CONFIG_H  -g -O2   -c /home/ghost/apcu-5.1.7/apcu-5.1.7/apc.c -o apc.lo 
mkdir .libs
 cc -D_GNU_SOURCE -DZEND_ENABLE_STATIC_TSRMLS_CACHE=1 -I. -I/home/ghost/apcu-5.1.7/apcu-5.1.7 -DPHP_ATOM_INC -I/home/ghost/apcu-5.1.7/apcu-5.1.7/include -I/home/ghost/apcu-5.1.7/apcu-5.1.7/main -I/home/ghost/apcu-5.1.7/apcu-5.1.7 -I/opt/lampp/include/php -I/opt/lampp/include/php/main -I/opt/lampp/include/php/TSRM -I/opt/lampp/include/php/Zend -I/opt/lampp/include/php/ext -I/opt/lampp/include/php/ext/date/lib -DHAVE_CONFIG_H -g -O2 -c /home/ghost/apcu-5.1.7/apcu-5.1.7/apc.c  -fPIC -DPIC -o .libs/apc.o
In file included from /home/ghost/apcu-5.1.7/apcu-5.1.7/apc_sma.h:34:0,
                 from /home/ghost/apcu-5.1.7/apcu-5.1.7/apc_pool.h:33,
                 from /home/ghost/apcu-5.1.7/apcu-5.1.7/apc_cache.h:36,
                 from /home/ghost/apcu-5.1.7/apcu-5.1.7/apc.c:35:
/home/ghost/apcu-5.1.7/apcu-5.1.7/apc_sma_api.h:46:5: error: unknown type name ‘zend_long’
     zend_long size;              /* size of this free block */
     ^
/home/ghost/apcu-5.1.7/apcu-5.1.7/apc_sma_api.h:47:5: error: unknown type name ‘zend_long’
     zend_long offset;            /* offset in segment of this block */
     ^
In file included from /home/ghost/apcu-5.1.7/apcu-5.1.7/apc_pool.h:36:0,
                 from /home/ghost/apcu-5.1.7/apcu-5.1.7/apc_cache.h:36,
                 from /home/ghost/apcu-5.1.7/apcu-5.1.7/apc.c:35:
/home/ghost/apcu-5.1.7/apcu-5.1.7/apc_pool_api.h:142:14: error: unknown type name ‘zend_string’
 PHP_APCU_API zend_string* apc_pstrcpy(zend_string *str, apc_pool* pool);
              ^
/home/ghost/apcu-5.1.7/apcu-5.1.7/apc_pool_api.h:142:39: error: unknown type name ‘zend_string’
 PHP_APCU_API zend_string* apc_pstrcpy(zend_string *str, apc_pool* pool);
                                       ^
/home/ghost/apcu-5.1.7/apcu-5.1.7/apc_pool_api.h:143:14: error: unknown type name ‘zend_string’
 PHP_APCU_API zend_string* apc_pstrnew(unsigned char *buf, size_t buf_len, apc_pool* pool);
              ^
In file included from /home/ghost/apcu-5.1.7/apcu-5.1.7/apc_cache.h:40:0,
                 from /home/ghost/apcu-5.1.7/apcu-5.1.7/apc.c:35:
/home/ghost/apcu-5.1.7/apcu-5.1.7/apc_cache_api.h:44:5: error: unknown type name ‘zend_string’
     zend_string *str;     /* the key for this cached entry */
     ^
/home/ghost/apcu-5.1.7/apcu-5.1.7/apc_cache_api.h:53:5: error: unknown type name ‘zend_long’
     zend_long ttl;  /* the ttl on this specific entry */
     ^
/home/ghost/apcu-5.1.7/apcu-5.1.7/apc_cache_api.h:54:5: error: unknown type name ‘zend_long’
     zend_long ref_count;/* the reference count of this entry */
     ^
/home/ghost/apcu-5.1.7/apcu-5.1.7/apc_cache_api.h:55:5: error: unknown type name ‘zend_long’
     zend_long mem_size; /* memory used */
     ^
/home/ghost/apcu-5.1.7/apcu-5.1.7/apc_cache_api.h:67:5: error: unknown type name ‘zend_long’
     zend_long nhits;            /* number of hits to this slot */
     ^
/home/ghost/apcu-5.1.7/apcu-5.1.7/apc_cache_api.h:82:5: error: unknown type name ‘zend_long’
     zend_long nhits;                /* hit count */
     ^
/home/ghost/apcu-5.1.7/apcu-5.1.7/apc_cache_api.h:83:5: error: unknown type name ‘zend_long’
     zend_long nmisses;              /* miss count */
     ^
/home/ghost/apcu-5.1.7/apcu-5.1.7/apc_cache_api.h:84:5: error: unknown type name ‘zend_long’
     zend_long ninserts;             /* insert count */
     ^
/home/ghost/apcu-5.1.7/apcu-5.1.7/apc_cache_api.h:85:5: error: unknown type name ‘zend_long’
     zend_long nexpunges;            /* expunge count */
     ^
/home/ghost/apcu-5.1.7/apcu-5.1.7/apc_cache_api.h:86:5: error: unknown type name ‘zend_long’
     zend_long nentries;             /* entry count */
     ^
/home/ghost/apcu-5.1.7/apcu-5.1.7/apc_cache_api.h:87:5: error: unknown type name ‘zend_long’
     zend_long mem_size;             /* used */
     ^
/home/ghost/apcu-5.1.7/apcu-5.1.7/apc_cache_api.h:101:5: error: unknown type name ‘zend_long’
     zend_long nslots;            /* number of slots in cache */
     ^
/home/ghost/apcu-5.1.7/apcu-5.1.7/apc_cache_api.h:102:5: error: unknown type name ‘zend_long’
     zend_long gc_ttl;            /* maximum time on GC list for a slot */
     ^
/home/ghost/apcu-5.1.7/apcu-5.1.7/apc_cache_api.h:103:5: error: unknown type name ‘zend_long’
     zend_long ttl;               /* if slot is needed and entry's access time is older than this ttl, remove it */
     ^
/home/ghost/apcu-5.1.7/apcu-5.1.7/apc_cache_api.h:104:5: error: unknown type name ‘zend_long’
     zend_long smart;             /* smart parameter for gc */
     ^
/home/ghost/apcu-5.1.7/apcu-5.1.7/apc_cache_api.h:139:44: error: unknown type name ‘zend_long’
                                            zend_long size_hint,
                                            ^
/home/ghost/apcu-5.1.7/apcu-5.1.7/apc_cache_api.h:140:44: error: unknown type name ‘zend_long’
                                            zend_long gc_ttl,
                                            ^
/home/ghost/apcu-5.1.7/apcu-5.1.7/apc_cache_api.h:141:44: error: unknown type name ‘zend_long’
                                            zend_long ttl,
                                            ^
/home/ghost/apcu-5.1.7/apcu-5.1.7/apc_cache_api.h:142:44: error: unknown type name ‘zend_long’
                                            zend_long smart,
                                            ^
/home/ghost/apcu-5.1.7/apcu-5.1.7/apc_cache_api.h:216:11: error: unknown type name ‘zend_string’
           zend_string *key,
           ^
/home/ghost/apcu-5.1.7/apcu-5.1.7/apc_cache_api.h:223:61: error: unknown type name ‘zend_string’
 PHP_APCU_API zend_bool apc_cache_update(apc_cache_t* cache, zend_string *key, apc_cache_updater_t updater, void* data);
                                                             ^
/home/ghost/apcu-5.1.7/apcu-5.1.7/apc_cache_api.h:230:68: error: unknown type name ‘zend_string’
 PHP_APCU_API apc_cache_entry_t* apc_cache_find(apc_cache_t* cache, zend_string *key, time_t t);
                                                                    ^
/home/ghost/apcu-5.1.7/apcu-5.1.7/apc_cache_api.h:236:60: error: unknown type name ‘zend_string’
 PHP_APCU_API zend_bool apc_cache_fetch(apc_cache_t* cache, zend_string *key, time_t t, zval **dst);
                                                            ^
/home/ghost/apcu-5.1.7/apcu-5.1.7/apc_cache_api.h:245:70: error: unknown type name ‘zend_string’
 PHP_APCU_API apc_cache_entry_t* apc_cache_exists(apc_cache_t* cache, zend_string *key, time_t t);
                                                                      ^
/home/ghost/apcu-5.1.7/apcu-5.1.7/apc_cache_api.h:250:61: error: unknown type name ‘zend_string’
 PHP_APCU_API zend_bool apc_cache_delete(apc_cache_t* cache, zend_string *key);
                                                             ^
/home/ghost/apcu-5.1.7/apcu-5.1.7/apc_cache_api.h:272:65: error: unknown type name ‘zend_string’
 PHP_APCU_API zend_bool apc_cache_make_key(apc_cache_key_t* key, zend_string *str);
                                                                 ^
/home/ghost/apcu-5.1.7/apcu-5.1.7/apc_cache_api.h:290:55: error: unknown type name ‘zend_string’
 PHP_APCU_API zval* apc_cache_stat(apc_cache_t* cache, zend_string *key, zval *stat);
                                                       ^
/home/ghost/apcu-5.1.7/apcu-5.1.7/apc_cache_api.h:390:116: error: unknown type name ‘zend_long’
 PHP_APCU_API void apc_cache_entry(apc_cache_t *cache, zval *key, zend_fcall_info *fci, zend_fcall_info_cache *fcc, zend_long ttl, zend_long now,
                                                                                                                    ^
In file included from /home/ghost/apcu-5.1.7/apcu-5.1.7/apc_cache.h:40:0,
                 from /home/ghost/apcu-5.1.7/apcu-5.1.7/apc.c:35:
/home/ghost/apcu-5.1.7/apcu-5.1.7/apc_cache_api.h:390:131: error: unknown type name ‘zend_long’
 PHP_APCU_API void apc_cache_entry(apc_cache_t *cache, zval *key, zend_fcall_info *fci, zend_fcall_info_cache *fcc, zend_long ttl, zend_long now,
                                                                                                                                   ^
In file included from /home/ghost/apcu-5.1.7/apcu-5.1.7/apc.c:36:0:
/home/ghost/apcu-5.1.7/apcu-5.1.7/apc_globals.h:44:5: error: unknown type name ‘zend_long’
     zend_long shm_segments;      /* number of shared memory segments to use */
     ^
/home/ghost/apcu-5.1.7/apcu-5.1.7/apc_globals.h:45:5: error: unknown type name ‘zend_long’
     zend_long shm_size;          /* size of each shared memory segment (in MB) */
     ^
/home/ghost/apcu-5.1.7/apcu-5.1.7/apc_globals.h:46:5: error: unknown type name ‘zend_long’
     zend_long entries_hint;      /* hint at the number of entries expected */
     ^
/home/ghost/apcu-5.1.7/apcu-5.1.7/apc_globals.h:47:5: error: unknown type name ‘zend_long’
     zend_long gc_ttl;            /* parameter to apc_cache_create */
     ^
/home/ghost/apcu-5.1.7/apcu-5.1.7/apc_globals.h:48:5: error: unknown type name ‘zend_long’
     zend_long ttl;               /* parameter to apc_cache_create */
     ^
/home/ghost/apcu-5.1.7/apcu-5.1.7/apc_globals.h:49:2: error: unknown type name ‘zend_long’
  zend_long smart;             /* smart value */
  ^
In file included from /home/ghost/apcu-5.1.7/apcu-5.1.7/zend_smart_str.h:23:0,
                 from /home/ghost/apcu-5.1.7/apcu-5.1.7/apc.c:41:
/home/ghost/apcu-5.1.7/apcu-5.1.7/zend_smart_str_public.h:23:2: error: unknown type name ‘zend_string’
  zend_string *s;
  ^
In file included from /home/ghost/apcu-5.1.7/apcu-5.1.7/apc.c:41:0:
/home/ghost/apcu-5.1.7/apcu-5.1.7/zend_smart_str.h: In function ‘smart_str_alloc’:
/home/ghost/apcu-5.1.7/apcu-5.1.7/zend_smart_str.h:56:10: warning: implicit declaration of function ‘ZSTR_LEN’ [-Wimplicit-function-declaration]
   len += ZSTR_LEN(str->s);
          ^
/home/ghost/apcu-5.1.7/apcu-5.1.7/zend_smart_str.h: In function ‘smart_str_free’:
/home/ghost/apcu-5.1.7/apcu-5.1.7/zend_smart_str.h:71:3: warning: implicit declaration of function ‘zend_string_release’ [-Wimplicit-function-declaration]
   zend_string_release(str->s);
   ^
/home/ghost/apcu-5.1.7/apcu-5.1.7/zend_smart_str.h: In function ‘smart_str_0’:
/home/ghost/apcu-5.1.7/apcu-5.1.7/zend_smart_str.h:79:3: warning: implicit declaration of function ‘ZSTR_VAL’ [-Wimplicit-function-declaration]
   ZSTR_VAL(str->s)[ZSTR_LEN(str->s)] = '\0';
   ^
/home/ghost/apcu-5.1.7/apcu-5.1.7/zend_smart_str.h:79:19: error: subscripted value is neither array nor pointer nor vector
   ZSTR_VAL(str->s)[ZSTR_LEN(str->s)] = '\0';
                   ^
/home/ghost/apcu-5.1.7/apcu-5.1.7/zend_smart_str.h: In function ‘smart_str_appendc_ex’:
/home/ghost/apcu-5.1.7/apcu-5.1.7/zend_smart_str.h:85:19: error: subscripted value is neither array nor pointer nor vector
  ZSTR_VAL(dest->s)[new_len - 1] = ch;
                   ^
/home/ghost/apcu-5.1.7/apcu-5.1.7/zend_smart_str.h:86:20: error: lvalue required as left operand of assignment
  ZSTR_LEN(dest->s) = new_len;
                    ^
/home/ghost/apcu-5.1.7/apcu-5.1.7/zend_smart_str.h: In function ‘smart_str_appendl_ex’:
/home/ghost/apcu-5.1.7/apcu-5.1.7/zend_smart_str.h:91:9: warning: passing argument 1 of ‘memcpy’ makes pointer from integer without a cast [-Wint-conversion]
  memcpy(ZSTR_VAL(dest->s) + ZSTR_LEN(dest->s), str, len);
         ^
In file included from /usr/include/features.h:367:0,
                 from /usr/include/assert.h:35,
                 from /home/ghost/apcu-5.1.7/apcu-5.1.7/apc.h:49,
                 from /home/ghost/apcu-5.1.7/apcu-5.1.7/apc.c:34:
/usr/include/i386-linux-gnu/bits/string3.h:50:1: note: expected ‘void * restrict’ but argument is of type ‘int’
 __NTH (memcpy (void *__restrict __dest, const void *__restrict __src,
 ^
In file included from /home/ghost/apcu-5.1.7/apcu-5.1.7/apc.c:41:0:
/home/ghost/apcu-5.1.7/apcu-5.1.7/zend_smart_str.h:92:20: error: lvalue required as left operand of assignment
  ZSTR_LEN(dest->s) = new_len;
                    ^
/home/ghost/apcu-5.1.7/apcu-5.1.7/zend_smart_str.h: At top level:
/home/ghost/apcu-5.1.7/apcu-5.1.7/zend_smart_str.h:95:75: error: unknown type name ‘zend_string’
 static zend_always_inline void smart_str_append_ex(smart_str *dest, const zend_string *src, zend_bool persistent) {
                                                                           ^
/home/ghost/apcu-5.1.7/apcu-5.1.7/zend_smart_str.h: In function ‘smart_str_append_ex’:
/home/ghost/apcu-5.1.7/apcu-5.1.7/zend_smart_str.h:96:29: warning: passing argument 2 of ‘smart_str_appendl_ex’ makes pointer from integer without a cast [-Wint-conversion]
  smart_str_appendl_ex(dest, ZSTR_VAL(src), ZSTR_LEN(src), persistent);
                             ^
/home/ghost/apcu-5.1.7/apcu-5.1.7/zend_smart_str.h:89:32: note: expected ‘const char *’ but argument is of type ‘int’
 static zend_always_inline void smart_str_appendl_ex(smart_str *dest, const char *str, size_t len, zend_bool persistent) {
                                ^
/home/ghost/apcu-5.1.7/apcu-5.1.7/zend_smart_str.h: At top level:
/home/ghost/apcu-5.1.7/apcu-5.1.7/zend_smart_str.h:105:74: error: unknown type name ‘zend_long’
 static zend_always_inline void smart_str_append_long_ex(smart_str *dest, zend_long num, zend_bool persistent) {
                                                                          ^
/home/ghost/apcu-5.1.7/apcu-5.1.7/zend_smart_str.h: In function ‘smart_str_append_unsigned_ex’:
/home/ghost/apcu-5.1.7/apcu-5.1.7/zend_smart_str.h:113:17: warning: implicit declaration of function ‘zend_print_ulong_to_buf’ [-Wimplicit-function-declaration]
  char *result = zend_print_ulong_to_buf(buf + sizeof(buf) - 1, num);
                 ^
/home/ghost/apcu-5.1.7/apcu-5.1.7/zend_smart_str.h:113:17: warning: initialization makes pointer from integer without a cast [-Wint-conversion]
/home/ghost/apcu-5.1.7/apcu-5.1.7/apc.c: In function ‘apc_flip_hash’:
/home/ghost/apcu-5.1.7/apcu-5.1.7/apc.c:336:57: warning: passing argument 2 of ‘zend_hash_get_current_data_ex’ from incompatible pointer type [-Wincompatible-pointer-types]
     while ((entry = zend_hash_get_current_data_ex(hash, &pos)) != NULL) {
                                                         ^
In file included from /opt/lampp/include/php/Zend/zend.h:286:0,
                 from /opt/lampp/include/php/main/php.h:35,
                 from /home/ghost/apcu-5.1.7/apcu-5.1.7/apc.h:69,
                 from /home/ghost/apcu-5.1.7/apcu-5.1.7/apc.c:34:
/opt/lampp/include/php/Zend/zend_hash.h:182:14: note: expected ‘void **’ but argument is of type ‘Bucket ** {aka struct bucket **}’
 ZEND_API int zend_hash_get_current_data_ex(HashTable *ht, void **pData, HashPosition *pos);
              ^
/home/ghost/apcu-5.1.7/apcu-5.1.7/apc.c:336:21: error: too few arguments to function ‘zend_hash_get_current_data_ex’
     while ((entry = zend_hash_get_current_data_ex(hash, &pos)) != NULL) {
                     ^
In file included from /opt/lampp/include/php/Zend/zend.h:286:0,
                 from /opt/lampp/include/php/main/php.h:35,
                 from /home/ghost/apcu-5.1.7/apcu-5.1.7/apc.h:69,
                 from /home/ghost/apcu-5.1.7/apcu-5.1.7/apc.c:34:
/opt/lampp/include/php/Zend/zend_hash.h:182:14: note: declared here
 ZEND_API int zend_hash_get_current_data_ex(HashTable *ht, void **pData, HashPosition *pos);
              ^
/home/ghost/apcu-5.1.7/apcu-5.1.7/apc.c:338:61: error: macro "zend_hash_update" requires 6 arguments, but only 3 given
             zend_hash_update(new_hash, Z_STR_P(entry), &data);
                                                             ^
/home/ghost/apcu-5.1.7/apcu-5.1.7/apc.c:338:13: error: ‘zend_hash_update’ undeclared (first use in this function)
             zend_hash_update(new_hash, Z_STR_P(entry), &data);
             ^
/home/ghost/apcu-5.1.7/apcu-5.1.7/apc.c:338:13: note: each undeclared identifier is reported only once for each function it appears in
/home/ghost/apcu-5.1.7/apcu-5.1.7/apc.c:340:68: error: macro "zend_hash_index_update" requires 5 arguments, but only 3 given
             zend_hash_index_update(new_hash, Z_LVAL_P(entry), &data);
                                                                    ^
/home/ghost/apcu-5.1.7/apcu-5.1.7/apc.c:340:13: error: ‘zend_hash_index_update’ undeclared (first use in this function)
             zend_hash_index_update(new_hash, Z_LVAL_P(entry), &data);
             ^
/home/ghost/apcu-5.1.7/apcu-5.1.7/apc.c:342:9: warning: implicit declaration of function ‘Z_TRY_ADDREF’ [-Wimplicit-function-declaration]
         Z_TRY_ADDREF(data);
         ^
In file included from /opt/lampp/include/php/Zend/zend.h:850:0,
                 from /opt/lampp/include/php/main/php.h:35,
                 from /home/ghost/apcu-5.1.7/apcu-5.1.7/apc.h:69,
                 from /home/ghost/apcu-5.1.7/apcu-5.1.7/apc.c:34:
/opt/lampp/include/php/Zend/zend_variables.h:57:48: warning: passing argument 1 of ‘_zval_ptr_dtor’ from incompatible pointer type [-Wincompatible-pointer-types]
 #define zval_ptr_dtor(zval_ptr) _zval_ptr_dtor((zval_ptr) ZEND_FILE_LINE_CC)
                                                ^
/home/ghost/apcu-5.1.7/apcu-5.1.7/apc.c:345:5: note: in expansion of macro ‘zval_ptr_dtor’
     zval_ptr_dtor(&data);
     ^
/opt/lampp/include/php/Zend/zend_variables.h:51:15: note: expected ‘zval ** {aka struct _zval_struct **}’ but argument is of type ‘zval * {aka struct _zval_struct *}’
 ZEND_API void _zval_ptr_dtor(zval **zval_ptr ZEND_FILE_LINE_DC);
               ^
Makefile:183: recipe for target 'apc.lo' failed
make: *** [apc.lo] Error 1`

**Comment by remicollet** [comment]
Version 5 is for PHP 7.x only, and you are obviously trying to compile against 5.x

You need to use version 4.x
