### ISSUE TITLE
memory leak?

### ISSUE THREAD

**Issue by kowach** [krakjoe/apcu#221]
`PHP Fatal error:  Allowed memory size of 335544320 bytes exhausted (tried to allocate 8606212256851192992 bytes) in ...`

8 exabytes :rofl: of ram

I upgraded from PHP 5.6 to PHP 7.0.14 (and APCu 5.1.7) and I noticed memory errors while deleting cache

    $apc=apc_cache_info('user');
    foreach($apc['cache_list'] as &$item) {
        if( preg_match($regexToDelete, $item['info']) ) {  // here it breaks
            apc_delete($item['info']);
        } 
    }

So I dumped items info strings larger then 1k and I found one apc key merged with it's value and with some other keys and values, one big binary blob....
This bug happens at random request and sometimes hangs out my php-fpm service.

**Comment by krakjoe** [comment]
Can you try latest sources in git please ?

**Comment by kowach** [comment]
It seems that latest source works, no errors so far.

**Comment by kowach** [comment]
There were no memory errors, also no more `apc_fetch(): Error at offset 1653 of 1658 bytes`.

**Comment by krakjoe** [comment]
The release was done.
