### ISSUE TITLE
Windows 2012  AppCrash

### ISSUE THREAD

**Issue by Kal74** [krakjoe/apcu#227]
I try to use APCU with PHP 7.0 on Windows server 2012 R2.
All the versions I tried x64/x84 TS/NTS crash when trying to access the same key from 2 different threads.

To reproduce it:
PHP 7.0.15 from http://windows.php.net/downloads/releases/php-7.0.15-nts-Win32-VC14-x86.zip
APCU 5.1.8 from http://windows.php.net/downloads/pecl/releases/apcu/5.1.8/php_apcu-5.1.8-7.0-nts-vc14-x64.zip
php.ini is the default production one with the following lines:
    extension_dir = "ext"
    extension=php_apcu.dll

test.php contain:
    apcu_add('foo', 'BAR');

Run 2 PHP server (like it would be done by Apache):
php -S 127.0.0.1:81
php -S 127.0.0.1:82
After few refresh between http://127.0.0.1:81/test.php and http://127.0.0.1:82/test.php PHP crash.

Thanks to have a look.
Best regards.

**Comment by Kal74** [comment]
The problem occur also when test is made over Windows 10.

**Comment by Stricted** [comment]
have you an crash log for this?

**Comment by weltling** [comment]
@Kal74 Looks like you hit [this issue](https://github.com/krakjoe/apcu/issues/67), which is a wontfix atm.

Thanks.

**Comment by tifabien** [comment]
It's quite annoying also for me to not having apcu working on Windows as it would improve my app performance a lot (caching composer autoloading files on my symfony app improve performance x3)
What could be alternatives to apcu for caching files on windows if it's too much work?

Thanks!

**Comment by Stricted** [comment]
as an alternatie for windows in currently only know https://pecl.php.net/package/WinCache

**Comment by tifabien** [comment]
Thanks @Stricted I'll have a look !
