### ISSUE TITLE
segfault ... error 4 in apcu.so

### ISSUE THREAD

**Issue by aensley** [krakjoe/apcu#228]
Creating an issue from my comment based on your feedback https://github.com/krakjoe/apcu/issues/172#issuecomment-258161547

PHP-FPM keeps dying at seemingly random intervals, but only when I use APCu from the code. I utilize APCu for small object caching. Each request caches/accesses between 5 and 500 objects (rarely more). PHP-FPM is living an average of 1.5 hours, and never survives more than 3.

If I remove all references to `apcu_*` functions from our PHP code, PHP-FPM lives forever.

dmesg shows thousands of these errors:

```
[7829072.537831] php-fpm7.0[11498]: segfault at 10 ip 00007f1c8c674cfa sp 00007ffdf67ec870 error 4 in apcu.so[7f1c8c66f000+12000]
```

And the PHP-FPM log shows this:

```
[31-Oct-2016 19:57:53] WARNING: [pool www] child 17557 exited on signal 11 (SIGSEGV - core dumped) after 20.115447 seconds from start
```

The `seconds from start` varies widely for each error.

Environment info:

* Ubuntu 16.04
* Kernel version: 4.4.0-45 (livepatched)
* Apache 2.4.18
* PHP 7.0.13 (PHP-FPM7.0)
* APCu 5.1.3

These are all the latest stable versions available in the official Ubuntu repositories. I'm not comfortable compiling from source or using a PPA to get newer versions unless absolutely necessary.

I run Canonical livepatch to keep the kernel up-to-date without rebooting.

```ShellSession
me@server:~# sudo canonical-livepatch status
kernel: 4.4.0-45.66-generic
fully-patched: true
version: "16.1"
```

**Comment by krakjoe** [comment]
You must use an up to date version of APCu.

**Comment by aensley** [comment]
@krakjoe

> These are all the latest stable versions available in the official Ubuntu repositories. I'm not comfortable compiling from source or using a PPA to get newer versions unless absolutely necessary.

What would you recommend I do to run 5.1.8 on Ubuntu 16.04?

**Comment by aensley** [comment]
@krakjoe 

I really want to get this working or at least give you a valid bug report. How do I get APCu on Ubuntu 16.04? The [installation instructions on php.net](http://php.net/manual/en/apcu.installation.php) are notably lacking and 5.1.3 is the latest version available for Ubuntu 16.04 (xenial): https://launchpad.net/ubuntu/+source/php-apcu

Can you point me toward some documentation or tutorial that will help? Thanks in advance.

**Comment by staabm** [comment]
@aensley the url you mentioned https://launchpad.net/ubuntu/+source/php-apcu mentionends a 
`Latest upload: 5.1.8+4.0.11-1`... it seems there you get anything you need?

**Comment by aensley** [comment]
@staabm That's for Zesty (ubuntu 17.04), which hasn't been released yet (scheduled for April 13). The latest stable version of Ubuntu is 16.10, and latest LTS is 16.04. Both Ubuntu versions only offer up to version 5.1.3 for APCu.

**Comment by staabm** [comment]
you are right, I missed that (already deleted the comment in the meantime)
