### ISSUE TITLE
How do I get APCu 5.1.8 on Ubuntu 16.04?

### ISSUE THREAD

**Issue by aensley** [krakjoe/apcu#230]
You keep closing my issues (#228) as invalid bug reports, but I honestly have no idea how to satisfy all of your requirements. The only one I can't figure out is getting the latest version of APCu on Ubuntu 16.04.

The [installation instructions on php.net](http://php.net/manual/en/apcu.installation.php) are notably lacking, and 5.1.3 is the latest version available for Ubuntu 16.04 (xenial): https://launchpad.net/ubuntu/+source/php-apcu

Can you point me toward documentation or a tutorial as a starting point for doing this? I'd like to get you a valid bug report so that something I believe is a real problem can be tested and fixed. For the good of the community (there were several others on #172 with the same problem), how do I do this?

**Comment by aensley** [comment]
For anyone else wondering the same thing, [Ondřej Surý's PPA](https://launchpad.net/~ondrej/+archive/ubuntu/php) has the most up-to-date APCu extension (and PHP and other extensions)

**Comment by dugwood** [comment]
You can compile it and install it by following the https://github.com/krakjoe/apcu/blob/master/INSTALL manual.

**Comment by aensley** [comment]
Thank you for the link @dugwood, but there is no way I'm going to compile from source for production servers.

**Comment by dugwood** [comment]
That's what Ondřej Surý does... and I do it for https://github.com/varnish/hitch or specific Varnish modules... And that's what debian package maintainers do...
I agree that's simpler to `apt-get install`, but sometimes it's better to compile things when you need freshness. Just don't forget that Ubuntu/Debian comes with a lot of libraries that you don't have to install by hand for compiling. For example `libxml` library is available as `libxml-dev` on Debian. Really easy.
You can close the bug now that PPA is up to date (5.1.8 as I can see)

**Comment by aensley** [comment]
True. This issue is resolved.

**Comment by Smiley-k** [comment]
How did you solved this problem ?

**Comment by dugwood** [comment]
@Smiley-k just look above, @aensley used the PPA: https://github.com/krakjoe/apcu/issues/230#issuecomment-284016441 => https://launchpad.net/~ondrej/+archive/ubuntu/php
