### ISSUE TITLE
pecl-apcu disables mmap when configure is called with --enable-apcu-mmap [PHP Bug #74211]

### ISSUE THREAD

**Issue by Takios** [krakjoe/apcu#234]
Hello,

I'm copying the bug I reported on php.net (#74211) here (your README tells users to report bugs on github, but the pecl-apcu page creates a new bug on php.net which is quite confusing).

When calling ./configure --enable-apcu-mmap, the script decides to not use mmap so it uses shm instead, but when omitting that option it does use mmap.

./configure --help only documents disable-apcu-mmap, so either the documentation is wrong or the implementation because clearly "enable-apcu-mmap" is changing the behaviour in a neither expected nor documented way.

PHP Version: 7.1.2
APCU Version: 5.1.8

Reproduced on Gentoo and openSUSE Tumbleweed.

Greetings
Fabian

Test script:
---------------
#!/bin/bash

wget "https://pecl.php.net/get/apcu-5.1.8.tgz"
tar xzf apcu-5.1.8.tgz
cd apcu-5.1.8/
phpize
./configure --enable-apcu-mmap | grep "checking if APCu will use mmap or shm"

Expected result:
----------------
checking if APCu will use mmap or shm... mmap

Actual result:
--------------
checking if APCu will use mmap or shm... shm

**Comment by Takios** [comment]
Fix confirmed. Thank you!

**Comment by remicollet** [comment]
Also see 83bb71a50a0355888ea6289aea53ccc6d8c0d40a
