### ISSUE TITLE
error: ‘IS_CONSTANT_ARRAY’ undeclared (first use in this function) case IS_CONSTANT_ARRAY:

### ISSUE THREAD

**Issue by phpapi** [krakjoe/apcu#241]
`PHP 5.6.30 (cli) (built: Mar 26 2017 01:30:22) 
Copyright (c) 1997-2016 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2016 Zend Technologies`

`CentOS Linux release 7.3.1611 (Core)`

I'm trying install the apc ext in php.  use pecl or compile package got this same error

`/bin/sh /root/APC-3.1.9/libtool --mode=compile cc  -I. -I/root/APC-3.1.9 -DPHP_ATOM_INC -I/root/APC-3.1.9/include -I/root/APC-3.1.9/main -I/root/APC-3.1.9 -I/usr/local/webmaster/php5/include/php -I/usr/local/webmaster/php5/include/php/main -I/usr/local/webmaster/php5/include/php/TSRM -I/usr/local/webmaster/php5/include/php/Zend -I/usr/local/webmaster/php5/include/php/ext -I/usr/local/webmaster/php5/include/php/ext/date/lib  -DHAVE_CONFIG_H  -g -O2   -c /root/APC-3.1.9/php_apc.c -o php_apc.lo 
 cc -I. -I/root/APC-3.1.9 -DPHP_ATOM_INC -I/root/APC-3.1.9/include -I/root/APC-3.1.9/main -I/root/APC-3.1.9 -I/usr/local/webmaster/php5/include/php -I/usr/local/webmaster/php5/include/php/main -I/usr/local/webmaster/php5/include/php/TSRM -I/usr/local/webmaster/php5/include/php/Zend -I/usr/local/webmaster/php5/include/php/ext -I/usr/local/webmaster/php5/include/php/ext/date/lib -DHAVE_CONFIG_H -g -O2 -c /root/APC-3.1.9/php_apc.c  -fPIC -DPIC -o .libs/php_apc.o
/bin/sh /root/APC-3.1.9/libtool --mode=compile cc  -I. -I/root/APC-3.1.9 -DPHP_ATOM_INC -I/root/APC-3.1.9/include -I/root/APC-3.1.9/main -I/root/APC-3.1.9 -I/usr/local/webmaster/php5/include/php -I/usr/local/webmaster/php5/include/php/main -I/usr/local/webmaster/php5/include/php/TSRM -I/usr/local/webmaster/php5/include/php/Zend -I/usr/local/webmaster/php5/include/php/ext -I/usr/local/webmaster/php5/include/php/ext/date/lib  -DHAVE_CONFIG_H  -g -O2   -c /root/APC-3.1.9/apc_cache.c -o apc_cache.lo 
 cc -I. -I/root/APC-3.1.9 -DPHP_ATOM_INC -I/root/APC-3.1.9/include -I/root/APC-3.1.9/main -I/root/APC-3.1.9 -I/usr/local/webmaster/php5/include/php -I/usr/local/webmaster/php5/include/php/main -I/usr/local/webmaster/php5/include/php/TSRM -I/usr/local/webmaster/php5/include/php/Zend -I/usr/local/webmaster/php5/include/php/ext -I/usr/local/webmaster/php5/include/php/ext/date/lib -DHAVE_CONFIG_H -g -O2 -c /root/APC-3.1.9/apc_cache.c  -fPIC -DPIC -o .libs/apc_cache.o
/root/APC-3.1.9/apc_cache.c: In function ‘_apc_cache_user_update’:
/root/APC-3.1.9/apc_cache.c:815:63: error: ‘IS_CONSTANT_INDEX’ undeclared (first use in this function)
             switch(Z_TYPE_P((*slot)->value->data.user.val) & ~IS_CONSTANT_INDEX) {
                                                               ^
/root/APC-3.1.9/apc_cache.c:815:63: note: each undeclared identifier is reported only once for each function it appears in
/root/APC-3.1.9/apc_cache.c:817:22: error: ‘IS_CONSTANT_ARRAY’ undeclared (first use in this function)
                 case IS_CONSTANT_ARRAY:
                      ^
make: *** [apc_cache.lo] Error 1`

**Comment by remicollet** [comment]
You are trying to build "APC" which is EOL (not APCU)

**Comment by remicollet** [comment]
BTW, on CentOS 7.3, see https://rpms.remirepo.net/wizard/
All PHP versions and most PHP extensions available there. No need to build from sources.
