### ISSUE TITLE
5.1.8 or 5.1.9dev

### ISSUE THREAD

**Issue by aelsharawi** [krakjoe/apcu#243]
Hello

why the default repo is for beta version

and if i WANT THE STABLE I have to get the tag
https://github.com/krakjoe/apcu/tree/v5.1.8

**Comment by Stricted** [comment]
because tags = releases

**Comment by aelsharawi** [comment]
thanks for quick reply, shall I use the 5.1.8 for production server better than 5.1.9dv?

`cd /svr-setup
git clone https://github.com/krakjoe/apcu/tree/v5.1.8
cd apcu
/usr/local/bin/phpize
./configure --with-php-config=/usr/local/bin/php-config
make -j2
make install`

**Comment by aelsharawi** [comment]
when entering
clone https://github.com/krakjoe/apcu/tree/v5.1.8
I got
fatal: repository 'https://github.com/krakjoe/apcu/tree/v5.1.8/' not found

**Comment by aelsharawi** [comment]
i got it

`$ git clone will give you the whole repository.

After the clone, you can list the tags with $ git tag -l and then checkout a specific tag:

$ git checkout tags/<tag_name>

Even better, checkout and create a branch (otherwise you will be on a branch named after the revision number of tag):

$ git checkout tags/<tag_name> -b <branch_name>`

**Comment by aelsharawi** [comment]
but we shall be on 5.1.8 ? correct?

**Comment by Stricted** [comment]
5.1.8 is the newest version for php7
for php5 you need 4.0.11

**Comment by aelsharawi** [comment]
so not recommend to use 5.1.9dev for production, thanks alot

I'm on php7 so will use 5.1.8
