### ISSUE TITLE
APCIterator zend heap corruption

### ISSUE THREAD

**Issue by staabm** [krakjoe/apcu#245]
not sure this is of any help, let me document it either way

in our app using php 7.0.18 and apcu 5.1.8  on ubuntu16lts we experience zend heap corruptions.

![image](https://cloud.githubusercontent.com/assets/120441/25484918/2a55a3c6-2b5c-11e7-8653-662e2b1de270.png)

the corruptions disappeared when commenting the following method:
(from https://github.com/staabm/thincache/blob/89bece45fad18bbdd58950e975c901e7978c1055/src/thincache/CacheApc.php#L109)

```php
<?php
    public function getRegex($regexKey, $limit = 100) {
        $regexKey = $this->cacheKey($regexKey);
      // regexKey containts "#www.handyflash.mst16/development@6528/rocket/sysmonitor/events/[^/]+#"
      
        $it = new APCIterator('user', $regexKey, APC_ITER_ALL, $limit, APC_LIST_ACTIVE);
        self::$requestStats['get']++;
        $res = array();
        foreach($it as $k => $v) {
            // wrap keys into static-keys so the caller can pass those apc-keys back into the cache-api,
            // without double-prefixing/namespacing issues
            $v['key'] = new CacheKeyStatic($v['key']);
            $res[] = $v;
        }
        return $res;
    }
```

backtraces of my problem can be found https://gist.github.com/staabm/453e96ff0507f054a6a651c6ebaf7a83#file-gistfile1-txt

**Comment by staabm** [comment]
we used this code on php 5.6 and apc successfully for years. could the problem be related to the actual regex used?

**Comment by staabm** [comment]
we see this kind of errors on more systems recently.

`#[^/]+/development@6647/rocket/metrics/default/[^/]+#` the $regexKey used in some situations seems also be a bit more "greedy".

I would guess the zend heap corruption depends on the cached data (e.g. some specific string cache-key used which results in a heap corruption when matching it against this `$regexKey`).

I narrowed it down a bit: The error also happens with the APCUIterator, not just the APCIterator. The code above seems to be causing it, as the app runs without heap corruptions when adding a hard `return array()` in the first line of it.

**Comment by staabm** [comment]
is my error related to https://bugs.php.net/bug.php?id=59938 ?

**Comment by nikic** [comment]
Is this issue resolved by the 5.1.9 release?

**Comment by staabm** [comment]
I need some time to get this deployed and tested in production

**Comment by nikic** [comment]
Can this be closed?

**Comment by staabm** [comment]
I am still trying... we just got 5.1.9 into production...I will give you a ping.

**Comment by staabm** [comment]
I will close this issue for now and will come back to it after I got negative results from our production node.
