### ISSUE TITLE
when a NUL char is used as key, apcu_fetch(array) truncates the key

### ISSUE THREAD

**Issue by nicolas-grekas** [krakjoe/apcu#247]
```php
apcu_store(array("a\0b" => 'foo'));
print_r(apcu_fetch(array("a\0b")));
```
output:
```
Array
(
    [a] => foo
)
```
expected:
```
Array
(
    [a<non-displayed-nul>b] => foo
)
```

**Comment by 7snovic** [comment]
I think that the expected result here is : `[a\0b] => foo` while as I see that the actual cache index is `a\0b`

**Comment by nicolas-grekas** [comment]
@7snovic nowhere else are values "addlshashed"
this would be inconsistent with the way non-array calls behave (`apcu_store("a\0b", 'foo')`).

**Comment by 7snovic** [comment]
@nicolas-grekas I will try to give an explanation for this ASAP.
