### ISSUE TITLE
apcu_fetch may return values causing zend_mm_corruption or segfaults when custom serializer is used. 

### ISSUE THREAD

**Issue by TysonAndre** [krakjoe/apcu#248]
I assume the values get incorrectly referenced counted, or have the wrong garbage collection flags

Affects the following serializers:

- Unrecognized serializer names `apc.serializer=nonsense`
- Igbinary (including latest)
- Blank (Somehow, still treated differently from `apc.serializer=default` or omitting that option)

Also, it seems like apcu treats `serializer="default"` differently from this.

Script to reproduce this (Can reproduce this with CLI invocation, as well as httpd worker process. Haven't tried other modes):

```php
<?php
// igbinaryapcutest.php:  Originally meant to debug igbinary, can debug other serializers

function build_array() {
    return [
        'params' => 2,
        'construct' => ['a'],
        'x1' => 'y',
        'x2' => 'y',
        'x3' => 'y',
        'x4' => 'y',
        'x5' => 'y',
        'x6' => 0,
    ];
}

class MyClass {
    private $_params;

    public function __construct($params) {
        debug_zval_dump($params);
        $this->_params = $params;
        debug_zval_dump($params);
        $this->_params['ids'] = [4];
        $this->_params['loadValue'] = 'x';
        unset($this->_params['params']);
    }
}

function setup() {
    apcu_delete('mytestkey');
    apcu_store('mytestkey', build_array());
}

function test_apcu_fetch() {
    // Or store second?
    $value = apcu_fetch('mytestkey');
    echo "Fetching the value initially stored into apcu:\n";
    debug_zval_dump($value);
    echo "Done dumping initial fetch\n\n";

    new MyClass($value);
    echo "\$value was passed by value, not reference. After instantiating class, the array \$value gets modified\n";
    debug_zval_dump($value);

    echo "\nAnd calling apcu_fetch again, the original data is preserved (8 keys, params=2)\n";
    debug_zval_dump(apcu_fetch('mytestkey'));
}
echo "Using apc serializer: " . ini_get('apc.serializer') . "\n";
setup();
test_apcu_fetch();
```

Observed results:

- `php -d apc.enable_cli=1 -d extension=$HOME/php-7.1.3-fast-install/lib/php/extensions/no-debug-non-zts-20160303/apcu.so --no-php-ini  -d apc.enable_cli=1  -d apc.serializer=nonsense igbinaryapcutest.php` : Crashes; $value isn't modified
- `php -d apc.enable_cli=1 -d extension=$HOME/php-7.1.3-fast-install/lib/php/extensions/no-debug-non-zts-20160303/apcu.so --no-php-ini  -d apc.enable_cli=1  -d apc.serializer=igbinary igbinaryapcutest.php` : Varies based on igbinary version. The master branch of igbinary seems to work properly (doesn't segfault, but results are wrong). In older versions, it segmentation faults. Before segfaulting, $value unexpectedly gets modified.even though it was passed by value, not reference
- `php -d apc.enable_cli=1 -d extension=$HOME/php-7.1.3-fast-install/lib/php/extensions/no-debug-non-zts-20160303/apcu.so --no-php-ini  -d apc.enable_cli=1  -d apc.serializer=php igbinaryapcutest.php` : Works

Software versions used for testing:

PHP: 7.1.3 NTS (did incomplete testing with php 7.1.5)
APCU: Affects latest master, as well as 5.1.8 and 5.1.7 , haven't tried earlier versions.
Igbinary: master seems to work, older versions (7.1.2?) have issues. Maybe it's related to fixes in how igbinary handles references.

php-config output:

```
Usage: /php-7.1.3-fast-install/bin/php-config [OPTION]
Options:
  --prefix            [/php-7.1.3-fast-install]
  --includes          [-I/php-7.1.3-fast-install/include/php -I/php-7.1.3-fast-install/include/php/main -I/php-7.1.3-fast-install/include/php/TSRM -I/php-7.1.3-fast-install/include/php/Zend -I/php-7.1.3-fast-install/include/php/ext -I/php-7.1.3-fast-install/include/php/ext/date/lib]
  --ldflags           [ -L/usr/lib/x86_64-linux-gnu]
  --libs              [-lcrypt   -lz -lexslt -lresolv -lcrypt -lreadline -lncurses -lpq -lrt -lpq -lstdc++ -lgmp -lpng -lz -ljpeg -lcurl -lbz2 -lz -lrt -lm -ldl -lnsl  -lxml2 -lssl -lcrypto -lcurl -lxml2 -lssl -lcrypto -ldl -lm -licui18n -licuuc -licudata -ldl -lm -licuio -lxml2 -lxml2 -lcrypt -lxml2 -lxml2 -lxml2 -lxml2 -lxslt -lxml2 -lssl -lcrypto -lcrypt ]
  --extension-dir     [/php-7.1.3-fast-install/lib/php/extensions/no-debug-non-zts-20160303]
  --include-dir       [/php-7.1.3-fast-install/include/php]
  --man-dir           [/php-7.1.3-fast-install/php/man]
  --php-binary        [/php-7.1.3-fast-install/bin/php]
  --php-sapis         [ cli fpm phpdbg cgi]
  --configure-options [--prefix=/php-7.1.3-fast-install --enable-phpdbg --enable-fpm --with-pdo-mysql=mysqlnd --with-mysqli=mysqlnd --with-pgsql --with-pdo-pgsql --with-pdo-sqlite --enable-intl --with-pear --with-gd --with-jpeg-dir=/usr --with-png-dir=/usr --enable-exif --enable-zip --with-zlib --with-zlib-dir=/usr --enable-soap --enable-xmlreader --with-xsl --with-curl=/usr --with-xmlrpc --enable-sysvsem --enable-sysvshm --enable-shmop --enable-pcntl --with-readline --enable-mbstring --with-curl --with-gettext --enable-sockets --with-bz2 --with-openssl --with-gmp --enable-bcmath --enable-calendar --enable-ftp --enable-sysvmsg]
  --version           [7.1.3]
  --vernum            [70103]
```

**Comment by TysonAndre** [comment]
I'm still able to reproduce this with the latest apcu master branch and `-d apc.serializer=nonsense`

**Comment by nikic** [comment]
@TysonAndre I believe I've fixed the issue with the "default" serializer (or "nonsense", it's all the same). Can you please verify that this resolves your issues? I've not tested igbinary.

**Comment by TysonAndre** [comment]
The fix looks good.

It looks like the output is now always the same, for apc.serializer=igbinary,

I don't see any valgrind errors when running the same unit test with extension=igbinary and apc.serializer=igbinary.

**Comment by csandanov** [comment]
Is it correct that not specifying `apc.serializer` shows `apc.serializer => php` in `php -i` instead of `default`?
