### ISSUE TITLE
php_apc.dll is not a valid Win32 application

### ISSUE THREAD

**Issue by alimohyudin** [krakjoe/apcu#249]
Hi, after googling since last 2 days I'm opening an issue here for the first time. My Php Version:
> PHP Version: 7.1.1
> Architecture:	x86
>Compiler:	MSVC14 (Visual C++ 2015)
>Thread Safety => enabled

Tried many different versions of apcu but got nothing work. For apcu version 
>7.1 Thread Safe (TS) x86

that I think is the closest to what my system is give me this error:

>PHP Warning:  PHP Startup: Unable to load dynamic library 'C:\\xampp\\php\\ext\\php_apc.dll' - %1 is not a valid Win32 application.\r\n in Unknown on line 0

Kindly help me out.
Thanks in advance.

**Comment by cmb69** [comment]
The name of the DLL should be php_apcu.dll, not php_apc.dll.

**Comment by nikic** [comment]
Did correcting the file name resolve this issue?

**Comment by alimohyudin** [comment]
I don't remember exactly but try to reinstall xampp with newer version of php.
