### ISSUE TITLE
Can the cache be shared in different php-fpm's pool?

### ISSUE THREAD

**Issue by taobig** [krakjoe/apcu#255]
In [issue 121](https://github.com/krakjoe/apcu/issues/121),  `fruitl00p` said 

> That way each pool could share their own APCu cache

For the above sentence, my understanding is that different pool has different APCu Cache.

In fact, I find different pool has the same parent process, so different pool share one APCu Cache
> ps -ef

> root           6218     1  0 12:27 ?        00:00:00 php-fpm: master process (/usr/local/php/etc/php-fpm.conf)
> nginx        6219  6195  0 12:27 ?        00:00:00 php-fpm: pool w2
> nginx        6220  6195  0 12:27 ?        00:00:00 php-fpm: pool w2
> nginx        6221  6195  0 12:27 ?        00:00:00 php-fpm: pool w2
> php-fpm   6222  6195  0 12:27 ?        00:00:00 php-fpm: pool www
> php-fpm   6223  6195  0 12:27 ?        00:00:00 php-fpm: pool www
> php-fpm   6224  6195  0 12:27 ?        00:00:00 php-fpm: pool www

So I doubt whether the cache can be shared in different php-fpm's pool ?

**Comment by dugwood** [comment]
See: https://github.com/krakjoe/apcu/issues/238

The cache IS shared (as it's run at the parent level).
