### ISSUE TITLE
No releases available for package "pecl.php.net/APCu"

### ISSUE THREAD

**Issue by longquan7** [krakjoe/apcu#256]
When I was build an image FROM arm64v8/php:5.6-fpm  when step at "RUN pecl install APCu geoip", it tell me No releases available for package "pecl.php.net/APCu" and No releases available for package "pecl.php.net/geoip"

**Comment by DepGr** [comment]
I am having the same issue while installing apcu on php7.2-apache2 docker official image: No releases available for package "pecl.php.net/apcu"..had you got any solution?

**Comment by longquan7** [comment]
@DepGr No,I don't take this problem

**Comment by nikic** [comment]
I don't know what's causing this problem, but I'm pretty sure that it doesn't have anything to do with apcu in particular and is a general PECL-related issue, and as such not something we can address.
