### ISSUE TITLE
APCU + Apache 32 bits + Windows 10 + php 7.1.9 TS, freeze when concurrent users

### ISSUE THREAD

**Issue by jorgecc** [krakjoe/apcu#258]
APCU + Apache 32 bits + Windows 10 + php 7.1.9 TS, freezes when around >10 **concurrent** users
I also tested with 7.x and its the same.

APCU runs fine for a single user but when i try a stress test with >10 concurrent users, it crashes Apache. Windows generates an event view but it says nothing :
"Nombre de la aplicación con errores: httpd.exe, versión: 2.4.25.0, marca de tiempo: 0x585506f4
Nombre del módulo con errores: ntdll.dll, versión: 10.0.14393.1378, marca de tiempo: 0x594a1295
Código de excepción: 0xc0000374"

**php.ini** (default libraries plus apcu extension)
  apc.enabled=1
  apc.shm_size=32M
  apc.ttl=7200
  apc.enable_cli=1

**php code:**
The php code tested doesn't use APCU.

I did the same test without APCU and it ran fine.

ps: its a bit tricky to test concurrent users, if you aren't fast enough then the test could run sequentially.

**Comment by dugwood** [comment]
If you're able to compile the extension under Windows, maybe you can test without RW locks: https://github.com/krakjoe/apcu/issues/259#issuecomment-363730090

That may be the same issue with locks not released (or something like this).
