### ISSUE TITLE
apcu.serializer=default results in segfault

### ISSUE THREAD

**Issue by csandanov** [krakjoe/apcu#260]
[Official apcu docs](http://php.net/manual/en/apc.configuration.php) says that the default value of `apc.serializer` is `default` when in fact it's `php`. Setting the value to `default` sometimes could result in segfaults, see https://bugs.php.net/bug.php?id=75344&thanks=3, also https://github.com/webtatic-rpms/php70w/issues/1.

**Comment by nikic** [comment]
Duplicate of issue #248, should be resolved by #277.
