### ISSUE TITLE
Two keys with same name, data but different timestamps

### ISSUE THREAD

**Issue by jokaorgua** [krakjoe/apcu#261]
have a dump after https://github.com/jokaorgua/prometheus_client_php lib work

> 
array(11) {
  ["type"]=>
  string(4) "user"
  ["key"]=>
  string(37) "prom:counter:error:meta"
  ["value"]=>
  string(105) "{"name":"error","help":"","type":"counter","labelNames":["param1","country","param3"]}"
  ["num_hits"]=>
  int(0)
  ["mtime"]=>
  int(1508955592)
  ["creation_time"]=>
  int(1508955592)
  ["deletion_time"]=>
  int(0)
  ["access_time"]=>
  int(1508955592)
  ["ref_count"]=>
  int(0)
  ["mem_size"]=>
  int(656)
  ["ttl"]=>
  int(0)
}
array(11) {
  ["type"]=>
  string(4) "user"
  ["key"]=>
  string(37) "prom:counter:error:meta"
  ["value"]=>
  string(105) "{"name":"error","help":"","type":"counter","labelNames":["param1","country","param3"]}"
  ["num_hits"]=>
  int(0)
  ["mtime"]=>
  int(1509005267)
  ["creation_time"]=>
  int(1509005267)
  ["deletion_time"]=>
  int(0)
  ["access_time"]=>
  int(1509005267)
  ["ref_count"]=>
  int(0)
  ["mem_size"]=>
  int(656)
  ["ttl"]=>
  int(0)
}
this dump was taken with the help of the following code

`foreach (new APCUIterator('/^prom:counter:.*:meta/') as $counter) {
var_dump($counter);
}`

how is this possible ?? two keys with one name, one data but different timestamps ?

**Comment by nikic** [comment]
The dump says `string(37) "prom:counter:error:meta"`, but that string has only 23 characters, not 37. Did you remove/change part of the key in this dump, or was this the actual output? If so, my guess it would be that the two keys differ in non-printable characters.

**Comment by jokaorgua** [comment]
removed confidential key name part which consists of [a-z]+. nothing about non-printable characters

**Comment by nikic** [comment]
@jokaorgua Thanks. Can you tell me which version of APCu this occurred on? APCu 5.1.9 fixed an issue that could cause corruption of keys returned by APCIterator. If this happened on an older version, it's quite likely that this is the reason.

**Comment by jokaorgua** [comment]
For sure it was in older version. This ticket was opened 5 months ago. During this time new ice age could happen.

**Comment by nikic** [comment]
As this problem has most likely been resolved in apcu 5.1.9, I'm closing this issue. Please reopen if it happens again on newer versions.
