### ISSUE TITLE
Fix nightly travis tests for php 7.3

### ISSUE THREAD

**Issue by TysonAndre** [krakjoe/apcu#268]
These broke after https://github.com/krakjoe/apcu/pull/267

A workaround is to manually build and install php master from source. A project which I work on had [travis scripts to do that for the 7.3 nightlies (See ci folder and .travis.yml)](https://github.com/runkit7/runkit7/blob/master/ci/install_php_nts.sh)

```
PHP_TAR_FILE="$PHP_FOLDER.tar.bz2"
if [ "$PHP_NTS_NORMAL_VERSION" == "7.3.0" ] ; then
	curl --location --verbose https://github.com/php/php-src/archive/master.zip -o php-src-master.zip
	unzip php-src-master.zip
	PHP_FOLDER=php-src-master
	pushd $PHP_FOLDER
	./buildconf --force
	popd
else
	curl --verbose https://secure.php.net/distributions/$PHP_TAR_FILE -o $PHP_TAR_FILE
	tar xjf $PHP_TAR_FILE
fi
```

(This approach is also useful for testing NTS/ZTS/debug/32-bit builds)

**Comment by nikic** [comment]
Looks like travis updated their nightly. Together with #276 the build failure is now fixed.

However, the AppVeyor build is broken.
