### ISSUE TITLE
Create a 5.1.10 release with fixes for igbinary, etc

### ISSUE THREAD

**Issue by TysonAndre** [krakjoe/apcu#280]
E.g. https://github.com/krakjoe/apcu/issues/248 is something that I'd want to see in a release - It prevents me from using igbinary.

**Comment by nikic** [comment]
Let's ping @remicollet about this.

**Comment by remicollet** [comment]
@krakjoe @nikic can you please the changelog entries in package.xml ?

When ok, I can run the 5.1.10 release

**Comment by nikic** [comment]
@remicollet I checked the changelog, should be good now.

**Comment by remicollet** [comment]
5.1.10 is now released.

I also bump version to 5.1.11dev

Please try to add changelog entry when committing / merging fix, it will be much more easier than having to dig in the git history for next release.
