### ISSUE TITLE
Serialization > igbinary

### ISSUE THREAD

**Issue by Nirjonadda** [krakjoe/apcu#282]
Please can you let me know that how to enable Serialization Support igbinary?

![screenshot00007](https://user-images.githubusercontent.com/6899856/36304083-aa4c841a-130e-11e8-8f41-1961eee85a6e.png)

**Comment by remicollet** [comment]
You need to enable it when building igbinary (or any other serializer).

Notthing to do on APCu side (which provide needed stuff for other extension)

**Comment by acgrid** [comment]
The fact is that, build apcu BEFORE igbinary, not the reversed way. Somehow it breaks my imagination.
Reference:
https://github.com/igbinary/igbinary/blob/d664bf08fb11f136b09951adbad89d4ebb35abfa/config.m4#L43
