### ISSUE TITLE
Caching curl handles

### ISSUE THREAD

**Issue by rinu** [krakjoe/apcu#292]
Is it possible to make caching curl handles work?
Currently the resource is cached in some way but it loses it's context. After fetching it knows it's a resource but has forgotten that it's a curl handle.
The only reason I want to do this is to keep a persistent connection to the remote server between requests. Curl already reuses persistent connections if the same handle is used multiple times.

**Comment by nikic** [comment]
No, it's not possible to cache resources in apcu. The code currently seems to allow this, but it will not actually work and may lead to crashes. Some checks to explicitly prohibit this should be added.

**Comment by rinu** [comment]
I understand that it's not possible now. My question was is this something this extension could do in the future? Caching the resources seemed like the most logical way to get what I'm after. The only option at the moment is to use external services to cache connections but the connection to that service also causes a small amount of overhead.

**Comment by nikic** [comment]
Nope, caching resources is impossible at the level of apcu. This would require core support. If you want to reuse curl handles, trying to add support for persistent curl resources should be a more fruitful endeavor.

**Comment by nikic** [comment]
I'm closing this one, as I don't believe it is possible to achieve this. The next version of apcu should also generate a warning if you try to store a resource (previously it was allowed, but might cause crashes later).
