### ISSUE TITLE
use apcu method with laravel command but not work

### ISSUE THREAD

**Issue by creamJelly** [krakjoe/apcu#294]
Hello
I'm working with laravel framework. I want to use apcu methods with laravel's command such as apcu_exists、apcu_store ……
I can use them with browser through get/post method.
Cache not change while using apcu method with command, and data can't be stored in memory.
`        if (false == apcu_exists("test")) {`
`            Log::info ("not exist");`
          `  apcu_store("test", 1);`
        `}`
        `else {`
            `$test = apcu_fetch("test");`
            `Log::info(json_encode($test));`
       ` }` 
The result always be "not exist", but I can't see anything in apcu

**Comment by nikic** [comment]
Did you set `apc.enable_cli=1`?

**Comment by creamJelly** [comment]
yes, I did.
I can console the data with apcu_fetch at the same time.
`        if (false == apcu_exists("test"))`
 `       {`
 `           Log::info ("not exist");`
    `        apcu_store("test", 1);`
    `        $result = apcu_fetch("test");`
  `          Log::info("after apcu_store : ".json_encode($result));`
 `       }`
I add two lines in "if" block, and console info is  "not exist", "after apcu_store : 1". But it still not work

**Comment by remicollet** [comment]
Notice that in CLI mode, the cache is not shared between various run, and is dropped as soon as the process exists

Using:

```
for ($i=0; $i<3; $i++) {
  if (apcu_exists("test")) {
    echo "exist\n";
  } else {
    echo "not exist\n";
    apcu_store("test", 1);
    $result = apcu_fetch("test");
    echo "after apcu_store : $result\n";
  }
}
```

Output

```
$ php /tmp/foo.php
not exist
after apcu_store : 1
exist
exist
```

Which is expected behavior

**Comment by creamJelly** [comment]
Thank you very much! 
I get your answer!
