### ISSUE TITLE
ApcuIterator->rewind is slow

### ISSUE THREAD

**Issue by staabm** [krakjoe/apcu#295]
in one of my websites I can see ApcuIterator->rewind() beeing the most expensive method call in the whole page.

![grafik](https://user-images.githubusercontent.com/120441/37274226-565426a2-25dc-11e8-8261-63e1d44d889b.png)

the call happens in the following spot (my app itself and the framework we use is closed source though)
https://github.com/staabm/thincache/blob/6585955bab9ccbc0b495462d7219776b336a6d5f/src/thincache/CacheApcu.php#L105-L121

if you need more information please feel free to ask.

env
```
This program makes use of the Zend Scripting Language Engine:
Zend Engine v3.0.0, Copyright (c) 1998-2017 Zend Technologies
    with Zend OPcache v7.0.27-1+ubuntu16.04.1+deb.sury.org+1, Copyright (c) 1999-2017, by Zend Technologies
    with blackfire v1.18.1~linux-x64-non_zts70, https://blackfire.io, by SensioLabs

APCu Version | 5.1.9
```

**Comment by nikic** [comment]
Assuming there are less than `$limit` entries in the result set, all the items will be fetched in `rewind()`. This involves iterating the *entire* cache and matching every entry, while under read-lock. If you have a large cache, I'd expect this to be quite slow.

**Comment by staabm** [comment]
just fyi. we can do the same stuff using the CacheMemcached adapter which is 15% faster

https://github.com/staabm/thincache/blob/6585955bab9ccbc0b495462d7219776b336a6d5f/src/thincache/CacheMemcached.php#L120-L170

not sure whether memcache is more efficient for this kind of operation or its just a difference of different storage size / cached-keys count.

**Comment by nikic** [comment]
@staabm A difference might be that apc currently is not making use of the pcre jit. That should be a relatively simple addition that might give a nice win here.

**Comment by nikic** [comment]
I've implemented two optimizations in #297: Using the PCRE JIT, which should help your case (I'm assuming many cache entries, few matching results) and preallocating the string keys (which helps in the case where are many results). For the second point, you can already try if using `APC_ITER_KEY|APC_ITER_VALUE` (or whatever parts you actually need) instead of `APC_ITER_ALL` will give you a performance improvement.

Based on a microbenchmark I'm seeing >1.5x speedup, though it will depend on the specific usecase.

**Comment by staabm** [comment]
> For the second point, you can already try if using APC_ITER_KEY|APC_ITER_VALUE (or whatever parts you actually need) instead of APC_ITER_ALL will give you a performance improvement.

its a pity, that I need both, keys and values in my use-case :-/.

but thanks for the hint, wasn't aware of this other constants.

**Comment by nikic** [comment]
@staabm You can use `APC_ITER_KEY|APC_ITER_VALUE` to get only the key and value. By default you get also 10 or so other entries (4 times, ttl, etc.)

**Comment by staabm** [comment]
ohh thx for the hint. I didnt read your answer and the php manual that way.

I tried `APC_ITER_KEY|APC_ITER_VALUE` which works as you said, but didn't yield a measurable perf benefit.

**Comment by nikic** [comment]
A new apcu version with APCIterator performance improvements has been released. It would be great if you could check if you see an improvement now.

**Comment by nikic** [comment]
Did you have a change to try this?

**Comment by staabm** [comment]
Sorry forgot it. Will do next week

**Comment by staabm** [comment]
I just tested with 5.1.11 and could not reproduce the problem anymore.

we still dont got 5.1.12 in production - yay for this LTS slow cycles :-/
