### ISSUE TITLE
can not install apcu-bc via release package

### ISSUE THREAD

**Issue by lichunqiang** [krakjoe/apcu#306]
Hi, The release package can not install `apcu-bc`,
```
configure: WARNING: unrecognized options: --enable-apcu-bc
```
I found that the __bc__ folder is empty.

**Comment by remicollet** [comment]
apcu-bc must be installed separately from https://github.com/krakjoe/apcu-bc

Of simply using the pecl command.

**Comment by lichunqiang** [comment]
@remicollet 

As https://secure.php.net/manual/en/apcu.installation.php document 

> If backward compatibility with the applicable parts of APC is required, APCu must be configured with the option --enable-apcu-bc.

So that make confuse.
