### ISSUE TITLE
Latest compatibility with older (5.5.9) PHP versions

### ISSUE THREAD

**Issue by dhaarbrink** [krakjoe/apcu#310]
Currently we still run (a security patched version of) PHP 5.5.9 on production, with APCu 4.0.6.

We want to upgrade APCu to a newer version, but I cannot find a compatibility guide or anything like that. 

What is the latest version of APCu I can run on PHP 5.5.9?

**Comment by remicollet** [comment]
See https://github.com/krakjoe/apcu/releases

Compatibility is given for each release.

**Comment by nikic** [comment]
Note that apcu for PHP 5 is no longer supported since the last release (4.0.11) in mid 2016.

**Comment by dhaarbrink** [comment]
Thanks @remicollet, I didn't realize they were target PHP versions.
@nikic, I realize that, thanks. We are planning on upgrading to PHP7 in the next couple of months, but need to upgrade APCu now, ahead of that.
