### ISSUE TITLE
PHP Startup: apc_mmap: mmap failed: in Unknown on line 0

### ISSUE THREAD

**Issue by mikehaertl** [krakjoe/apcu#314]
We run PHP with apcu inside a docker container based on Alpine 3.7. Since some time we see this in our logfiles and PHP fails to start:

> [09-Jul-2018 09:18:07] NOTICE: PHP message: PHP Fatal error:  PHP Startup: apc_mmap: mmap failed: in Unknown on line 0

It happens either immediately after firing up the container or after the container ran for quite a while (couple of days). The only workaround so far is to reboot the host machine.

We're also aware of #223, but we're not on Windows and our version is > 5.1.9

The image ran fine until we also added redis to the container - we're unsure if it's really related to that, though.

We first assumed a low mem issue. But `free` shows still quite a lot of memory available:

```
$ free -h
              total        used        free      shared  buff/cache   available
Mem:           1,9G        342M        1,1G         35M        524M        1,5G
Swap:          511M          0B        511M
```

### Versions and configurations

The full list of installed php7 Alpine packages:

```
php7-7.1.17-r0
php7-apcu-5.1.11-r0
php7-common-7.1.17-r0
php7-ctype-7.1.17-r0
php7-curl-7.1.17-r0
php7-dom-7.1.17-r0
php7-fpm-7.1.17-r0
php7-gd-7.1.17-r0
php7-intl-7.1.17-r0
php7-json-7.1.17-r0
php7-mbstring-7.1.17-r0
php7-mysqlnd-7.1.17-r0
php7-opcache-7.1.17-r0
php7-openssl-7.1.17-r0
php7-pdo-7.1.17-r0
php7-pdo_mysql-7.1.17-r0
php7-posix-7.1.17-r0
php7-session-7.1.17-r0
php7-soap-7.1.17-r0
php7-tokenizer-7.1.17-r0
php7-wddx-7.1.17-r0
php7-xml-7.1.17-r0
php7-xmlreader-7.1.17-r0
php7-zip-7.1.17-r0
```
We've only modified pm config in `/etc/php7/conf.d/www.conf` (it's a low-traffic dev server):

```
pm = dynamic
pm.max_children = 10
pm.min_spare_servers = 2
pm.max_spare_servers = 6
```

We've also mapped a config file into the container under `/etc/php7/zz-docker.conf`:

```ini
; The settings below are mainly copied from the php-fpm docker image.
[global]
error_log = /proc/self/fd/2

[www]
clear_env = no

; Ensure worker stdout and stderr are sent to the main error log.
catch_workers_output = yes

user = www-data
group = www-data

listen = /var/run/php7-fpm.sock
listen.owner = www-data
listen.group = www-data
listen.mode = 0660

; Safety measure: Frequently restart children
pm.max_requests = 200
```

**Comment by nikic** [comment]
To clarify, you did not modify any apcu settings, so you are using the default of `apc.shm_size=32M`?

**Comment by mikehaertl** [comment]
@nikic Oh, sorry, no. I forgot we map another file to `/etc/php7/90-productive.ini`. The content is:

```ini
memory_limit = 256M
upload_max_filesize = 64M
post_max_size = 64M
max_execution_time = 300
session.use_strict_mode = 1
session.gc_probability = 1
session.gc_divisor = 100
session.gc_maxlifetime = 3600

apc.shm_size=2G
apc.entries_hint=131072
```

**Comment by mikehaertl** [comment]
Argl - I now see that we probably *do* have a low mem issue. It seems APCu will allocate quite some bit of the 2GB when it starts up. And the machine only has about 1.5 GB free. Guess this explains the issue then.

Feel free to close, unless you think this is something that should be fixed in a better way (e.g. handle it more nicely without bringing php-fpm down).

**Comment by nikic** [comment]
Are you using a 32-bit or 64-bit operating system?

**Comment by nikic** [comment]
While mmap will not "use" the entire 2G allocation at once, it does some checks to make sure enough memory (or rather: swap space) are available, unless you're using overcommit_memory=1. We *could* perform the mmap with MAP_NORESERVE instead, which would allow the mmap to succeed but may make the application segfault at a later point in time when it physically runs out of memory. It might be possible to catch and handle that segfault and limit the memory segment size at that point, but I'd rather not go down that way. Just throwing a hard error at startup if the memory size is too large seems better.

**Comment by remicollet** [comment]
> Just throwing a hard error at startup if the memory size is too large seems better.

+1

**Comment by mikehaertl** [comment]
> Just throwing a hard error at startup if the memory size is too large seems better.

Sounds good to me. Does that mean the error message can be  improved a little? IMO it never hurts to be as explicit as possible, so something like this would really help the poor devop: "Failed to allocate 2G of mmap memory. You should probably reduce apc.shm_size."

**Comment by nikic** [comment]
The error message has been improved in #326 and some related issues have been fixed. The error is now:

> PHP Fatal error:  apc_mmap: Failed to mmap 322122547200 bytes. Is your apc.shm_size too large? in Unknown on line 0
