### ISSUE TITLE
Release 5.1.13

### ISSUE THREAD

**Issue by DaveRandom** [krakjoe/apcu#320]
Please can a release be tagged asap for the same reasons as https://github.com/krakjoe/apcu-bc/issues/28

**Comment by nikic** [comment]
@remicollet Can you please create a new release for apcu? I've updated the changelog in package.xml :)

**Comment by remicollet** [comment]
@nikic will take care of it tomorrow morning

**Comment by remicollet** [comment]
Released

**Comment by nikic** [comment]
Thanks Remi!
