### ISSUE TITLE
apcu_inc/apcu_dec aren't atomic

### ISSUE THREAD

**Issue by admin-altrooz** [krakjoe/apcu#332]
It is standard and expected with any caching mechanism that the increment and decrement operations be atomic, meaning that two concurrent increments are both guaranteed to be applied.  This does not seem to be the case with APCu, either versions 4.x or 5.x.  Therefore APCu can't be used to implement mutexes or assign unique ids.

**Comment by nikic** [comment]
Which apcu version are you using and in which case do you observe non-atomicity? Prior to version 5.1.12 apcu_inc/dec were non-atomic for the case where a new key was created by apcu_inc/dec. If that's the case you have in mind, please make sure you're using the latest version. If you are operating on existing keys only, then previous versions should also be atomic.

**Comment by tharlinsmith** [comment]
Sorry for the false alarm, we found where the race condition was in our own software.
