### ISSUE TITLE
apc_cache_info('user') returns no cache_list

### ISSUE THREAD

**Issue by Glandos** [krakjoe/apcu#34]
In every installed PHP applications I have, the function apc_cache_info is called with 'user' as mentionned in the doc of APC. Applications expect to find the cache_list key in the returned array. It seems that this array doesn't contains this key. However, calling apc_cache_info without parameter returns the expected array.

Is it deliberated? Shouldn't APCu be compatible with APC?

**Comment by remicollet** [comment]
Also see 83bb71a50a0355888ea6289aea53ccc6d8c0d40a
