### ISSUE TITLE
apcu_key_info() not documented

### ISSUE THREAD

**Issue by nikic** [krakjoe/apcu#342]
The apcu_key_info() function is currently not documented on php.net.

Implementation is at: https://github.com/krakjoe/apcu/blob/4bbdd30a04f9ca528dda79572ef54dd88b63778b/apc_cache.c#L1077

**Comment by andypost** [comment]
Is there any guide about how to add docs?

**Comment by nikic** [comment]
So in this case it should go something like:

 * Go to edit.php.net and log in using some method
 * Navigate to en/reference/apcu/functions
 * Right click -> Add new file and choose function.xml skeleton
 * Write docs ^^ It may be useful to look at a similar file like apcu-cache-info.xml
 * In the "Work in progress" section right click and submit patch for review
 * Post a link to the patch here, otherwise it's going to take a long time until someone sees it

**Comment by GeniusLe** [comment]
The patch has been submitted to take effect, please close the issue
https://www.php.net/manual/zh/function.apcu-key-info.php

**Comment by nikic** [comment]
Thanks!
