### ISSUE TITLE
Crash on PHP 7.3

### ISSUE THREAD

**Issue by trasher** [krakjoe/apcu#350]
Hi,

I do use APCu to hack on [GLPI](https://glpi-project.org), and with versions 5.1.13 and 5.1.14, this is not working ont the master branch of the project with PHP 7.3 RC6.

Error is:
```
==> /var/opt/remi/php73/log/php-fpm/error.log <==
[23-Nov-2018 10:16:24] WARNING: [pool www] child 32744 exited on signal 6 (SIGABRT) after 149.169478 seconds from start
[23-Nov-2018 10:16:24] NOTICE: [pool www] child 1271 started
```

Just tested with APCu 5.1.12, all is working fine.

Thank you!

**Comment by trasher** [comment]
A precision, I'm able to get things working using `apc.serializer='php'` in the configuration.

**Comment by nikic** [comment]
> A precision, I'm able to get things working using apc.serializer='php' in the configuration.

That's very useful to know. Can you determine the value that was cached (or maybe fetched) when the SIGABRT occurs? Or maybe get the backtrace from the core dump? (SIGABRT to me sounds like something triggered an assertion failure.)

**Comment by trasher** [comment]
Note that `apc.serializer='igbinary'` do work as well.
I cannot get a corecdump (had to disable it entirely, my system is unusable :/)

Not sure I would be able to know where it breaks (and what are the data), I'll try to grab the information...

**Comment by nikic** [comment]
A new version where apc.serializer=php is the default again has been released. Please tell me if you still experience any issues.
