### ISSUE TITLE
Error when installing version 5.1.15

### ISSUE THREAD

**Issue by Spea** [krakjoe/apcu#360]
I installed php `7.1.19` via brew and then tried to install apcu via `pecl install apcu`, but I get the following error:

```
/private/tmp/pear/temp/apcu/apc_sma.c:291:19: error: conflicting types for 'apc_sma_init'
PHP_APCU_API void apc_sma_init(apc_sma_t* sma, void** data, apc_sma_expunge_f expunge, int32_t num, size_t size, char *mask) {
                  ^
/private/tmp/pear/temp/apcu/apc_sma_api.h:85:19: note: previous declaration is here
PHP_APCU_API void apc_sma_init(
                  ^
1 error generated.
make: *** [apc_sma.lo] Error 1
ERROR: `make' failed
```

After taking a look at the [apcu_sma_init](https://github.com/krakjoe/apcu/blob/master/apc_sma_api.h#L87) header file it seems like the declaration was not adjusted when the types were changed to `size_t` [in this commit](https://github.com/krakjoe/apcu/commit/f3e0aebdfae10535020b0e5e2f21669da5fb7393)

**Comment by nikic** [comment]
Fixed in https://github.com/krakjoe/apcu/commit/39ab0ed00a41f8e6e3983f06435dbf31e5ba87ee. It would be great if one travis job ran on osx to avoid issues like this in the future. On Linux and Windows this compiled cleanly :/

**Comment by staabm** [comment]
Seems osx us supported by travis
https://docs.travis-ci.com/user/reference/osx

**Comment by nikic** [comment]
@staabm yeah, but iirc not with php preinstalled, so this will probably need a bit of extra setup.

**Comment by staabm** [comment]
I found the following examples, which might help

https://github.com/phpmyadmin/phpmyadmin/commit/9ecda4175b6c19c781cf23254da151bfa15eb81a#diff-354f30a63fb0907d4ad57269548329e3
https://github.com/kiler129/TravisCI-OSX-PHP

**Comment by Log1x** [comment]
Any chance of getting this pushed to PECL? This caused a good bit of downtime this morning. =(

**Comment by fatherswatch** [comment]
same error with 7.1.25 and 7.2.13

**Comment by nikic** [comment]
I've just published a new version that includes the build fix. Sorry for the delay!
