### ISSUE TITLE
Build fails with master again

### ISSUE THREAD

**Issue by BenMorel** [krakjoe/apcu#363]
It looks like #361 is back, apcu does not compile against master again:

https://travis-ci.community/t/php-nightly-outdated/1812/2
https://travis-ci.org/travis-ci/php-src-builder/jobs/478669880#L4543

**Comment by BenMorel** [comment]
This prevents builds against the PHP 7.4 branch in Travis CI:
https://travis-ci.community/t/add-php-7-4-branch-to-test-against/2179

**Comment by nikic** [comment]
Release with compat fixes is out.
