### ISSUE TITLE
Release apcu 5.1.17

### ISSUE THREAD

**Issue by nikic** [krakjoe/apcu#367]
@remicollet Could you please run an apcu release?

Only changes are compat fixes for 7.4 and 8.0. Needed to get PHP 7.4 builds on Travis :)

**Comment by remicollet** [comment]
yes, start working on it now

**Comment by remicollet** [comment]
Test build + test suite OK (Fedora 26-29, RHEL 6-8-Beta, i386, x86_64, NTS, ZTS, PHP 7.0, 71, 7.2, 7.3)

Tagged, Released and announced.

**Comment by nikic** [comment]
Thanks! I think the tag got lost somewhere though ^^

**Comment by remicollet** [comment]
indeed... forgot to push it, fixed now.

https://github.com/krakjoe/apcu/releases/tag/v5.1.17
