### ISSUE TITLE
apache2_switch_mpm: MPM prefork not found

### ISSUE THREAD

**Issue by vl-lapikov** [krakjoe/apcu#373]
**Problem**
Error thrown, when trying to install "apache2 libapache2-mod-php7.0 php-apcu" all together.

**Steps to Reproduce**

- Install docker 
- Create Dockerfile
```
FROM ubuntu:trusty

ARG DEBIAN_FRONTEND=noninteractive

RUN apt-get -qq update

RUN apt-get install -y software-properties-common language-pack-en-base

RUN LC_ALL=en_US.UTF-8 apt-add-repository -y ppa:ondrej/php

RUN apt-get -qq update

RUN apt-get -y install \
     apache2 \
     libapache2-mod-php7.0 \
     php7.0 \
     php-apcu
```
- Run `docker build .`

**Actual Result**
Error thrown
```
No module matches
apache2_switch_mpm: MPM prefork not found
libapache2-mod-php7.0: Could not switch to prefork MPM, not enabling PHP 7.0
```

**Workaround**
Moving `php-apcu` into separate `RUN apt-get -y install php-apcu` prevent the error. I am checking, is it a real solution.

**Comment by krakjoe** [comment]
Refer to package maintainer, we do not prepare these packages.

**Comment by vl-lapikov** [comment]
Thank you for quick answer. For reference, created bug here https://bugs.launchpad.net/ubuntu/+source/php-apcu/+bug/1818633
