### ISSUE TITLE
Won't compile with PHP 7.4.0beta2

### ISSUE THREAD

**Issue by YetiCGN** [krakjoe/apcu#382]
With the release of PHP 7.4 at the door, I wanted to test our application with the current beta. However, we rely on APCu and it currently doesn't compile - at least not with PECL:

    # pecl install apcu
    downloading apcu-5.1.17.tgz ...
    Starting to download apcu-5.1.17.tgz (94,814 bytes)
	.....................done: 94,814 bytes
	39 source files, building
	running: phpize7.4
	Configuring for:
	PHP Api Version:         20190529
	Zend Module Api No:      20190529
	Zend Extension Api No:   320190529
	configure.ac:161: warning: LTOPTIONS_VERSION is m4_require'd but not m4_defun'd
	build/libtool.m4:61: LT_INIT is expanded from...
	build/libtool.m4:99: AC_PROG_LIBTOOL is expanded from...
	configure.ac:161: the top level
	configure.ac:161: warning: LTSUGAR_VERSION is m4_require'd but not m4_defun'd
	build/libtool.m4:61: LT_INIT is expanded from...
	build/libtool.m4:99: AC_PROG_LIBTOOL is expanded from...
	configure.ac:161: the top level
	configure.ac:161: warning: LTVERSION_VERSION is m4_require'd but not m4_defun'd
	build/libtool.m4:61: LT_INIT is expanded from...
	build/libtool.m4:99: AC_PROG_LIBTOOL is expanded from...
	configure.ac:161: the top level
	configure.ac:161: warning: LTOBSOLETE_VERSION is m4_require'd but not m4_defun'd
	build/libtool.m4:61: LT_INIT is expanded from...
	build/libtool.m4:99: AC_PROG_LIBTOOL is expanded from...
	configure.ac:161: the top level
	configure:5199: error: possibly undefined macro: m4_ifval
		  If this token and others are legitimate, please use m4_pattern_allow.
		  See the Autoconf documentation.
	configure:8668: error: possibly undefined macro: _LT_SET_OPTIONS
	configure:8668: error: possibly undefined macro: LT_INIT
	ERROR: `phpize' failed

**Comment by nikic** [comment]
This doesn't look specific to apcu, but some kind of general autoconf issue. @petk Does this look familiar?

**Comment by petk** [comment]
Thanks for the ping. Checking out this soon... Yes, something related to the PHP build system itself.

**Comment by YetiCGN** [comment]
Thanks for your quick reply. By googling the error message, I found some very old threads from 2008 describing the a problem in the build system. I tried some of the steps, but to no avail. I stopped there, because I just tried it out of curiosity. 

I have however noticed that in your Travis config, there is no build for PHP 7.4, only for master = PHP 8.0-dev. Could you add that one just so we're sure ahead of time that it'll work?

**Comment by petk** [comment]
@YetiCGN installation of PHP 7.4 is rocket science. How did you manage to install it? 

Because this works ok (without any additional patches):

```sh
git clone git://github.com/php/php-src
cd php-src
git checkout PHP-7.4
docker run -it --rm -v `pwd`:/opt/php-src -w /opt/php-src alpine sh
apk add --no-cache make autoconf re2c bison gcc g++ libxml2-dev sqlite-dev openssl-dev
./buildconf
./configure --with-pear --with-openssl
make -j$(nproc)
make install
pecl update-channels pecl.php.net
pecl install apcu
vi /usr/local/lib/php.ini
# add there extension=apcu
php -m
```

Yes?

**Comment by petk** [comment]
I think I've found the issue here - it's the PHP PPA for Ubuntu and APT Debian packages where the new libtool is used and there is a very customized phpize script used which uses PHP 7.3 items Hm, I have no idea how exactly that launchpad works to send patches to at the moment, so probably this should be then fixed in the upstream of that particular APT repo.

https://bugs.launchpad.net/~ondrej

cc @oerdnj

**Comment by oerdnj** [comment]
I made no effort to compile any PECL extensions for PHP 7.4 so far. I usually start with rc1.

That’s said if you have any patches, I would be happy to accept them at github.com/ondrej/deb.sury.org/issues

**Comment by YetiCGN** [comment]
> @YetiCGN installation of PHP 7.4 is rocket science. How did you manage to install it?

Although I could get into that particular brand of rocket surgery if I had time (been using Linux since I think 1999 or 2000 and compiled my fair share of programs and kernels from source), I did get it from @oerdnj 's Ubuntu PPA actually:

    php7.4-cli/xenial,now 7.4.0~beta2-1+ubuntu16.04.1+deb.sury.org+1 amd64 [installed]

So, fair enough, I can wait till RC1. Or I could use your instructions, @petk.

**Comment by petk** [comment]
> So, fair enough, I can wait till RC1. Or I could use your instructions, @petk.

:+1: I suggest waiting for the repository and use that. Compiling PHP yourself for particular project is a very problematic and error prone thing which will complicate your and project's life. Also because of the future updates.

**Comment by YetiCGN** [comment]
It's just an experiment anyway to identify any issues way ahead of the usual update cycle, but not really necessary.
