### ISSUE TITLE
contradictory statements in INSTALL

### ISSUE THREAD

**Issue by tessus** [krakjoe/apcu#387]
The INSTALL file states the following:

```
Suggested Configuration (in your php.ini file)
  apc.enable_cli=1

[snip]

    apc.enable_cli       Mostly for testing and debugging.  Setting this enables APCu
                         for the CLI version of PHP.  Normally you wouldn't want to
                         create, populate and tear down the APCu cache on every CLI
                         request, but for various test scenarios it is handy to be
                         able to enable APCu for the CLI version of APCu easily.
```

While the explanation makes total sense, the suggested setting does not.

**Comment by LionsAd** [comment]
I actually do think that the INSTALL is wrong here. APCu since newer versions actually shares a cache with the cli.

**Comment by tessus** [comment]
This makes even less sense, because this would only be possible, if there was something like file caching. I don't see such a parameter for apc(u). Or the CLI would need some sort of server component to access shared memory, which is not available. (One could argue that php-fpm and/or another SAPI module was such a component, but one could exclusively use php cli.)
Either way, this situation needs clarification.

**Comment by LionsAd** [comment]
I agree that the suggested setting does not make sense. I was wrong and a cache is not shared with the cli.

**Comment by tessus** [comment]
@krakjoe what's your take on this?

**Comment by tessus** [comment]
apparently doesn't give a ....
