### ISSUE TITLE
apcu_store() and apcu_add() reject pairs with integer keys

### ISSUE THREAD

**Issue by ShiraNai7** [krakjoe/apcu#388]
Due to PHP's array key magic, it's impossible to create an array with string keys that are also valid integers - they get converted to actual integers.

The problem is that `apcu_store()` and `apcu_add()` reject such pairs:

```php
var_dump(apcu_store("12", "hello")); // bool(true)
var_dump(apcu_add("34", "hello")); // bool(true)
var_dump(apcu_store(["56" => "hello"])); // array(1) { [56] => int(-1) }
var_dump(apcu_store(["78" => "hello"])); // array(1) { [78] => int(-1) }
```

Perhaps `apc_store_helper` should cast all keys to strings?

**Comment by nikic** [comment]
Yeah, we should do that.
