### ISSUE TITLE
Extension failed to load on windows with PHP 7.4

### ISSUE THREAD

**Issue by evgeniymweb100** [krakjoe/apcu#390]
PHP: php-7.4.0-nts-Win32-vc15-x64.zip
APCu: php_apcu-5.1.18-7.3-nts-vc15-x64.zip

![зображення](https://user-images.githubusercontent.com/11403811/69936002-2937b280-14df-11ea-8fcb-cf35247ad338.png)

**Comment by Rarst** [comment]
I am assuming DLL version needs to fit the PHP release, 7.4 does not seem to be available on PECL yet... https://pecl.php.net/package/APCu/5.1.18/windows

**Comment by evgeniymweb100** [comment]
But in changelog i can see some 'compatibility with 7.4', so I assumed that dll can work with 7.4 as well. If no - can anyone tell, when 7.4 version will be available?

**Comment by cmb69** [comment]
Windows mass rebuilds of all PECL packages are scheduled for this week. **Snapshots** of APCu 5.1.8 are already [available](https://windows.php.net/downloads/pecl/snaps/apcu/5.1.18/) for **testing**.

**Comment by nikic** [comment]
Closing this as it's not something we can influence from the apcu side ... just need to wait for the rebuild or use the snapshots.

**Comment by cmb69** [comment]
Regular 7.4 DLLs are available now: https://pecl.php.net/package/APCu/5.1.18/windows
