### ISSUE TITLE
"apc.use_request_time" - Better understand or reconsider default

### ISSUE THREAD

**Issue by Krinkle** [krakjoe/apcu#391]
Hi,

For Wikipedia's deployment, and for the MediaWiki software in general, we're currently considering to turn this off everywhere ([patch](https://gerrit.wikimedia.org/r/#/c/mediawiki/core/+/578400/)).

-------

> If a value is saved with a TTL of X, then it should take ~X seconds for it to expire. A key may need to use low, often randomized, TTLs, and this behavior breaks such use cases.
> 
> The default `apc.use_request_time` value (1) assigns writes a timestamp equal to the web request timestamp. If a request has been going for Y seconds, then a TTL of X becomes (X-Y) as far as new requests can see, due to the "back-dating". If Y > X, then the value was effectively purged for all new requests. This can easily be tested via `sleep()`.

-------

I'd like to better understand why this setting is enabled by default. If there are cases we may've missed, I'd like to help document these better for the benefit of others (and to perhaps keep the default the afterall).

If not, perhaps it would make sense for the next major version to disable this as well.

Thanks!

/cc @AaronSchulz

**Comment by nikic** [comment]
I believe this is just a performance consideration, to avoid calling time() on every apc API call. I have no idea if this is still relevant nowadays or not.

**Comment by AaronSchulz** [comment]
From some quick profiling, I didn't notice a difference.
```
function testAPC( $use_req_time ) {
	ini_set( 'apc.use_request_time', (string)$use_req_time );

	$t = microtime( true );
	for ( $i = 0; $i < 1000000; ++$i ) {
		if ( !apcu_store( 'x', 'a', 10 ) ) {
			throw new Exception( "Failed" );
		}
	}
	var_dump( 'store', microtime( true ) - $t );

	$t = microtime( true );
	for ( $i = 0; $i < 1000000; ++$i ) {
		if ( apcu_fetch( 'x' ) === false ) {
			throw new Exception( "Failed" );
		}
	}
	var_dump( 'get', microtime( true ) - $t );
}
```

```
>>> testAPC(0);
string(5) "store"
float(0.75342202186584)
string(3) "get"
float(0.38800597190857)
=> null
>>> testAPC(1);
string(5) "store"
float(0.7548041343689)
string(3) "get"
float(0.38969397544861)
=> null
```
