### ISSUE TITLE
PHPStan hangs when apcu is active

### ISSUE THREAD

**Issue by swiffer** [krakjoe/apcu#394]
When running PHPStan on Windows (64bit, NTS, 7.4) with composer.json apcu_autoloader: true and checking files in parallel PHPStan hangs when creating multiple threads.

This seems to happen on Windows only (tried nts and ts builds).

This repo can be used to reproduce the problem: https://github.com/swiffer/apcu-autoloader-demo-phpstan

Ticket in PHPStan's repo: https://github.com/phpstan/phpstan/issues/3007

**Comment by nikic** [comment]
APCU on Windows does not work in multi-process mode (only multi-thread mode).

@krakjoe Maybe we should prevent this extension from compiling on Windows, to save people the trouble?

Also cc @cmb69 in case you care about apcu support on Windows. The tl;dr here is similar issues as with opcache. To support Windows properly we'd have to change the locking to work inter-process (easy) and make the whole SHM cache position-independent (hard), otherwise we get back to the same issue with mmap base addresses.

**Comment by cmb69** [comment]
As I understand it, APCu uses `shmget()` and friends (i.e. on Windows their custom implementations in tsrm/tsrm_win32.c). However, the Windows implementation has a flaw, namely that `IPC_PRIVATE` is not handled according to POSIX (in other words, is not private to the process). If this is going to be fixed (php-src/master?), APCu would still not work in multi-process mode, but at least there should be no crashes.

Something that might be done now (APCu only, no change to php-src) would be to store the PID in the SHM on Windows, and if that PID doesn't match, `apc_sma_init()` would error. That would keep APCu usable on Windows multi-thread mode SAPIs (mod_php) at least.

What do you think?

**Comment by nikic** [comment]
@cmb69 Possibly we can substitute the apc_shm implementation with simple malloc/free on Windows? That would be "private".

**Comment by swiffer** [comment]
just wanted to let you know, for me it's not a dealbreaker right now, just using windows in my dev environment, just was curious to see if it's not supported or I'm doing something wrong. Can not tell about the effort and if it's worth it

**Comment by cmb69** [comment]
> Possibly we can substitute the apc_shm implementation with simple malloc/free on Windows?

Oh, indeed, that would most likely be the most viable solution for now. In the long run, php/php-src#5519 appears to be an alternative which would not require changes to APCu.

**Comment by cmb69** [comment]
@swiffer, a "fix" for this issue has landed in php-src. You may want to check out the currently generated [snapshot builds](https://windows.php.net/downloads/snaps/php-7.3/rf33cf52/).

**Comment by swiffer** [comment]
i can confirm it's working in php-src 7.4 snapshot from today as well 👍
