### ISSUE TITLE
compiler warnings

### ISSUE THREAD

**Issue by thelounge-zz** [krakjoe/apcu#398]
/home/builduser/rpmbuild/BUILD/php-8.0.0/ext/apcu/apc_cache.c: In function ‘apc_cache_entry’:
/home/builduser/rpmbuild/BUILD/php-8.0.0/ext/apcu/apc_cache.c:1225:21: warning: increment of a boolean expression [-Wbool-operation]
 1225 |  if (APCG(recursion)++ == 0) {
      |                     ^~
/home/builduser/rpmbuild/BUILD/php-8.0.0/ext/apcu/apc_cache.c:1227:19: warning: decrement of a boolean expression [-Wbool-operation]
 1227 |    APCG(recursion)--;
      |                   ^~
/home/builduser/rpmbuild/BUILD/php-8.0.0/ext/apcu/apc_cache.c:1262:7: warning: decrement of a boolean expression [-Wbool-operation]
 1262 |   if (--APCG(recursion) == 0) {
      |       ^~
In file included from /home/builduser/rpmbuild/BUILD/php-8.0.0/main/php.h:127,
                 from /home/builduser/rpmbuild/BUILD/php-8.0.0/ext/apcu/apc.h:67,
                 from /home/builduser/rpmbuild/BUILD/php-8.0.0/ext/apcu/apc_sma.h:31,
                 from /home/builduser/rpmbuild/BUILD/php-8.0.0/ext/apcu/apc_sma.c:29:
/home/builduser/rpmbuild/BUILD/php-8.0.0/ext/apcu/apc_sma.c: In function ‘sma_deallocate’:
/home/builduser/rpmbuild/BUILD/php-8.0.0/ext/apcu/apc_sma.c:238:16: warning: comparison of unsigned expression >= 0 is always true [-Wtype-limits]
  238 |  assert(offset >= 0);
      |                ^~
/home/builduser/rpmbuild/BUILD/php-8.0.0/ext/apcu/apc_sma.c:238:16: warning: comparison of unsigned expression >= 0 is always true [-Wtype-limits]
  238 |  assert(offset >= 0);
      |                ^~
/home/builduser/rpmbuild/BUILD/php-8.0.0/ext/apcu/apc_signal.c: In function ‘apc_register_signal’:
/home/builduser/rpmbuild/BUILD/php-8.0.0/ext/apcu/apc_signal.c:116:9: warning: missing initializer for field ‘sa_mask’ of ‘struct sigaction’ [-Wmissing-field-initializers]
  116 |  struct sigaction sa = {{0}};
      |         ^~~~~~~~~
In file included from /usr/include/signal.h:226,
                 from /home/builduser/rpmbuild/BUILD/php-8.0.0/Zend/zend_signal.h:26,
                 from /home/builduser/rpmbuild/BUILD/php-8.0.0/Zend/zend.h:41,
                 from /home/builduser/rpmbuild/BUILD/php-8.0.0/main/php.h:31,
                 from /home/builduser/rpmbuild/BUILD/php-8.0.0/ext/apcu/apc.h:67,
                 from /home/builduser/rpmbuild/BUILD/php-8.0.0/ext/apcu/apc_signal.c:35:
/usr/include/bits/sigaction.h:46:16: note: ‘sa_mask’ declared here
   46 |     __sigset_t sa_mask;
      |                ^~~~~~~

**Comment by nikic** [comment]
You must be building something other than master.

**Comment by thelounge-zz** [comment]
where did i say that i build master?
apcu-5.1.18.tgz
