### ISSUE TITLE
5.1.19 Release

### ISSUE THREAD

**Issue by GrahamCampbell** [krakjoe/apcu#400]
What's the plan for the next release? 5.1.18 no longer works with PHP 8.0. ;)

**Comment by nikic** [comment]
I think it would make sense to make a release once PHP 8.0 RC1 is available, as that's when ABI is frozen.

Also, https://github.com/php-build/php-build/pull/638 is still not resolved.

**Comment by GrahamCampbell** [comment]
My decision there was not to include a master definition.

**Comment by derickr** [comment]
@GrahamCampbell Your decision is stubborn and not what people actually want and use it for. "master" is actually really useful, and you're being emotional and making an illogical decision.

**Comment by andypost** [comment]
Please create a beta release to allow install it via pecl and get more ways to test

**Comment by GrahamCampbell** [comment]
@andypost You can still install by downloading the source yourself, for now.

**Comment by ryanaslett** [comment]
Downloading the source requires us to rearchitect our docker container build process to add in "sometimes downloading from source, and adding a build step for it, and sometimes using a packaged pecl release.

So, for drupal, since APCu is part of our test suite, having a pre-release available simplifies the amount of work we have to do so that we can continue testing with php8.

**Comment by nikic** [comment]
At least from my side this should be ready for release now. Only open question is apcu-bc compatibility (https://github.com/krakjoe/apcu/commit/4184048429fa30b0ee2daaa83f4fe707b1ba7626#comments).

**Comment by nikic** [comment]
Now that apcu-bc compatibility for PHP 7 should be restored, @remicollet could you please create a new release? I updated the changelog just now.

**Comment by remicollet** [comment]
@nikic will take care of it in next hours

**Comment by remicollet** [comment]
5.1.19 is Released
