### ISSUE TITLE
add a build for php 8

### ISSUE THREAD

**Issue by swiffer** [krakjoe/apcu#404]
can the appveyor config be extended to support builds for php 8.0rc1+?

this is what xdebug has done in 3.0.0-beta1 to ease testing of php8.0 on windows.

**Comment by lourdas** [comment]
PHP 8.0 was released yesterday. We'd surely like a 8.0 build.

**Comment by nikic** [comment]
I'm happy to merge a PR, not familiar with the AppVeyor setup myself.

**Comment by swiffer** [comment]
i've simply added the variants to the matrix and it's working fine for me. #409 

additionally #395 should be merged as well as it's fixing some warnings in the travis config?

**Comment by swiffer** [comment]
Just use the latest artifacts from the master branch for PHP8

https://ci.appveyor.com/project/krakjoe/apcu

**Comment by grunk** [comment]
> Just use the latest artifacts from the master branch for PHP8

Thanks that works !

Would be nice to have it available on PECL with the others dll
