### ISSUE TITLE
apc_cache_info('user') compatibility issue

### ISSUE THREAD

**Issue by AVK93** [krakjoe/apcu#41]
When calling `apc_cache_info('user')`, the array keys seems to differ from apc's ones. 
With apcu I got: 

```
[nslots] => 4099
    [ttl] => 0
    [nhits] => 24
    [nmisses] => 42
    [ninserts] => 52
    [nentries] => 28
    [nexpunges] => 0
    [stime] => 1379344890
    [mem_size] => 58000
    [file_upload_progress] => 1
    [memory_type] => IPC shared
    [cache_list] => Array
        (
            [0] => Array
                (
                    [key] => Myapp__cake_core_cake_deu
                    [ttl] => 86313600
                    [nhits] => 0
                    [mtime] => 1379378443
                    [ctime] => 1379378443
                    [dtime] => 0
                    [atime] => 1379378443
                    [ref_count] => 0
                    [mem_size] => 584
                )
...
```

As far as I know, APC uses `num_entries` instead of `nentries` and `start_time` instead of `stime`. Also in the cache list entries, APC uses `info` instead of `key`. I think there are also more of these keys, but I currently have no apc installation to check them out. 

Is it possible to get apcu's apc_cache_info() full compatible with apc's one?

**Comment by ptdev** [comment]
Until there's a new official release with these key inconsistencies resolved so most package managers eventually pick it up, the goal of providing a drop-in replacement for apc on 5.5+ is a failed goal.
This breaks things on *a lot* of apps that have apc caching integration and is forcing developers to release fixes with aditional code to distinguish apc from apcu which imho defeats the whole purpose of it.
That said, I do agree that if keys were poorly named on the original apc in the first place, then apcu should continue to improve on that, but still maintain backwards compatibility with the old keys for a while. Maybe eventually start throwing some e_deprecated errors and eventually phase out the old keys.
But at this time, when there are still a lot of people migrating from 5.3 and 5.4 I think the returned arrays should be able to be accessed in exactly the same way as the original apc.
