### ISSUE TITLE
apcu_entry locks exclusive cache lock every time

### ISSUE THREAD

**Issue by dragon-dreamer** [krakjoe/apcu#411]
The `apcu_entry` function, which internally calls `apc_cache_entry`, locks writer (exclusive) lock on every call: https://github.com/krakjoe/apcu/blob/f7b32b7a9e952e186cb0cc0bbb8a2073e34f3b1b/apc_cache.c#L1219-L1230

What one might expect it to do is to actually lock the shared lock and upgrade it to exclusive only when necessary (when writing a cache entry). However, currently the function that is designed to keep the cache intact for most of the calls exclusively locks the whole cache each call.

**Comment by nikic** [comment]
There is no such thing as upgrading a shared lock to an exclusive lock. That would dead lock trivially if you had two threads with shared lock trying to upgrade to exclusive lock. Temporarily relinquishing the shared lock would violate the function contract.

This function should really be deprecated & removed, what it does doesn't make much sense (and can lead to deadlock on incorrect usage).

**Comment by dragon-dreamer** [comment]
You are right, that makes sense. I missed the point that there may be many threads changing cache contents. And I guess you are also right about deprecating this function. What was misleading to me, is that this function locks the cache completely every time you call it.

However, it would be nice to have some support to prevent possible cache stampede, which is not currently available out of the box. Probably something like a function which lets a single thread to recompute the cache entry (without locking the whole cache for that time), while all other threads receive old data.

**Comment by LionsAd** [comment]
Because there is lockless cmpxchg you can easily build this yourself on the application level.

It’s very simple to add per item locks that way.
