### ISSUE TITLE
5.1.19 ext won't load on PHP 8.0.0 on Windows, using NTS version

### ISSUE THREAD

**Issue by GenesisCraig** [krakjoe/apcu#414]
PHP error log claims it cannot "find" the full, but lists the correct path. Suspect some version support issue?

APCu 5.1.19, NTS, x64
PHP 8.0.0, x64, NTS
Windows Server 2016
IIS

**Comment by nikic** [comment]
Where did you get the php_apcu.dll?

**Comment by GenesisCraig** [comment]
This is the link I used on PECL:

https://windows.php.net/downloads/pecl/releases/apcu/5.1.19/php_apcu-5.1.19-7.4-nts-vc15-x64.zip

**Comment by nikic** [comment]
As the file name indicates, that's a build for 7.4. I believe the 8.0 build for your configuration is at https://ci.appveyor.com/project/krakjoe/apcu/builds/36557585/job/tntf2ao8ttuyp123/artifacts.

**Comment by GenesisCraig** [comment]
Thank you!  I had read in the changelog in PECL that 8.0 support had been added to that release and there was no separate php 8 download.

Will the release on appveyor.com be uploaded to pecl or should I always go to appveyor.com for new apcu builds?

**Comment by GenesisCraig** [comment]
Thank you!  I had read in the changelog in PECL that 8.0 support had been added to that release and there was no separate php 8 download.

Will the release on appveyor. be uploaded to pecl or should I always go to appveyor.com for new apcu builds?

**Comment by nikic** [comment]
The DLLs on PECL are automatically generated and should become available once the mass rebuild of extensions for PHP 8.0 is started. I'm not sure when that is going to happen though... The AppVeyor artifacts are something that can be used in the meantime.
