### ISSUE TITLE
Working with windows and FastCGI

### ISSUE THREAD

**Issue by HarryLT** [krakjoe/apcu#428]
Hi,
I know in the past APCu had issues when working in FastCGI mode,  I believe this was because of the way processes split under FastCGI and that does not work well with APCu.  Is this still an issue with the current release?
I am looking to run PHP 8 on windows using FastCGI (64 bit NTS).  Wincache is no longer being maintained so was hoping I could change to APCu.
Thank you for your help.
Harry

**Comment by nikic** [comment]
If you want to have an actually shared cached, you need to use a thread-based SAPI on Windows. Sharing the cache is not support for multi-process SAPIs on Windows, and cannot be supported without significant redesign.
