### ISSUE TITLE
Add a build for php current stable php 8.1.0

### ISSUE THREAD

**Issue by KGB1st** [krakjoe/apcu#429]
Please make PECL DLL for PHP 8.1 (x64, vs16, nts) as it possible.. Thx a lot!

**Comment by Gemorroj** [comment]
@cmb69 can you help?

**Comment by cmb69** [comment]
There are already [snapshot builds available](https://windows.php.net/downloads/pecl/snaps/apcu/5.1.21/). Mass rebuilds of all PECL packages should happen in 1-2 weeks. See also https://windows.php.net/#news-2021-12-02-1.

**Comment by cmb69** [comment]
[apcu 5.1.21 DLLs for PHP 8.1](https://pecl.php.net/package/APCu/5.1.21/windows) are now available.

I think this ticket can be closed.
