### ISSUE TITLE
Release 5.1.22

### ISSUE THREAD

**Issue by remicollet** [krakjoe/apcu#447]
As 5.1.21 is broken with 8.1 (minor) and 8.2 (segfauilt), what about releasing a 5.1.22 ?

P.S. 8.2.0RC1 being released with (very probably) final API/ABI

**Comment by nikic** [comment]
Sounds good

**Comment by remicollet** [comment]
Changelog:

* PHP 8.2 compatibility
* control panel: fix PHP 8.1 compatibility

@nikic do you want me to take care of the release process ?

**Comment by nikic** [comment]
@remicollet I added some more notes to the changelog. And yes, please create the PECL release, I haven't done one in ages...

**Comment by remicollet** [comment]
Released and uploaded to pecl.
