### ISSUE TITLE
Missing Windows DLL file

### ISSUE THREAD

**Issue by ruurdkrekt** [krakjoe/apcu#484]
The Windows DLL seems to be missing for the 5.1.22 release normally available on [the PECL website](https://pecl.php.net/package/APCU). Would it be possible for this to be added please?

**Comment by JamesShiers** [comment]
Any updates on the 5.1.22 DLL or where it can be found?

**Comment by ruurdkrekt** [comment]
No haven't heard anything as of yet. I also have emailed the PHP for Windows team, but no reply from them either.

**Comment by nikic** [comment]
DLLs on the PECL site are outside of our influence. But you can find up to date DLLs in our GA builds: https://github.com/krakjoe/apcu/actions/runs/4210917721 (scroll to "Artifacts" at the end).

**Comment by JamesShiers** [comment]
Thanks Nikic, 

I've saved that link for future reference... 

Has anybody found an updated version of the WinCache dll compatible with newer PHP release i.e. 8.2?

**Comment by ruurdkrekt** [comment]
Thanks @nikic

**Comment by InfinityMuenster** [comment]
Seems like the builds are expired now. Any mirror or other opportunity to get the PHP 8.2-64bit-TS.dll for Windows?

Thanks in advance.

**Comment by yolao** [comment]
expired !

**Comment by OwnerOfThisIsle** [comment]
Where to get those builds, when the GA builds expire?

**Comment by nikic** [comment]
There are newer builds on https://github.com/krakjoe/apcu/actions/runs/5203759037.

**Comment by OwnerOfThisIsle** [comment]
Thank you, but I am hesitating to use that build in a productive environment, because it is not tagged as an official release.
Is it recommended to use a build from most current master?

**Comment by yakatz** [comment]
> There are newer builds on https://github.com/krakjoe/apcu/actions/runs/5203759037.

These build artifacts are now expired. Can you add them to the Github Release so they are kept around?

**Comment by Connum** [comment]
See https://github.com/krakjoe/apcu/issues/450#issuecomment-1750401271 

As long as there is no official release of the Windows binaries, you can get a suitable php_apcu.dll for the 5.1.22 stable version here:
https://www.48design.com/en/news/2023/10/06/php_apcu-dll-5.1.22-windows-binaries-php-8.2/#download

**Comment by nikic** [comment]
DLLs for 5.1.23 are available at https://github.com/krakjoe/apcu/releases/tag/v5.1.23 now.
