### ISSUE TITLE
Segmentation fault in apache from apc_cache_find

### ISSUE THREAD

**Issue by danieladams** [krakjoe/apcu#49]
Basic Description
=============
We are getting segfaults with APCU 4.0.2 on PHP 5.5 on Apache HTTPD 2.2.3. They appear to relate to calls to apc_cache_find failing to find contents of memory at a location that has seemingly not been allocated.

Severity
=============
This is a serious bug that makes the host unusable until after HTTPD is restarted

Reproducing Error
=============
We are experiencing this error in production code but we do not have a test script at this time. The general scenario is that we start up HTTPD and the code runs fine on a host for several hours, with no segfaults. After a few hours, a request segfaults and after that point, all requests segfault until HTTPD is restarted. It appears to happen under times of relatively higher (but still absolutely low) levels of load - host averages are 0.2-1.0, CPU is 90+% idle, low number of requests overall.

Stacktrace/GDB output
=================
http://pastebin.com/Gbcd4gKE

**Comment by gunjanpatidar** [comment]
@krakjoe is it possible to detect a possible segmentation fault and return NULL. That should solve this for the most cases as this happens pretty infrequently.

**Comment by krakjoe** [comment]
According to other reports, this was fixed in later versions, upgrade to 4.0.6 or 4.0.7.
