### ISSUE TITLE
Create new release

### ISSUE THREAD

**Issue by nikic** [krakjoe/apcu#497]
@remicollet Would it be possible to create a new PECL release? I've updated the changelog in package.xml.

**Comment by andypost** [comment]
please release 5.1.23 with PHP 8.3 compatible tests

**Comment by ChristianArimond** [comment]
Please add Windows DLLs this time. Otherwise I guess I have to look for alternatives unfortunately :(

**Comment by nikic** [comment]
I've created the release myself, hopefully I got everything right. I've uploaded the Windows artifacts to the release at https://github.com/krakjoe/apcu/releases/tag/v5.1.23.

**Comment by andypost** [comment]
Thank you!
