### ISSUE TITLE
Store an \SplPriorityQueue 

### ISSUE THREAD

**Issue by soyuka** [krakjoe/apcu#505]
Is it expected to loose informations about the `\SplPriorityQueue`? (haven't tried with other SPL classes)

```php
$bar = new \SplPriorityQueue();
$bar->insert('a', 1);
var_dump($bar);
apcu_store('foo', $bar);
var_dump(apcu_fetch('foo'));
```

![20240318_16h49m14s_grim](https://github.com/krakjoe/apcu/assets/1321971/59181aaf-d500-4a5b-8718-5840e5a49665)

**Comment by nikic** [comment]
apcu supports any class that can be serialized, and it looks like SplPriorityQueue currently doesn't support this. I've filed an issue with PHP here: https://github.com/php/php-src/issues/14402
