### ISSUE TITLE
Missing apc_load_constants and apc_define_constants

### ISSUE THREAD

**Issue by xathien** [krakjoe/apcu#54]
I've been looking into upgrading our systems from 5.3.19 to 5.5.5, and APC 3.1.15 seems to be trampling memory, so I'm giving APCu a shot as a drop-in replacement. Dropped it in and... found two missing functions that we rely on. :)

Short of compiling hidef and figuring out how to implement it, are there any plans for having APCu provide these two functions?

Using PHP 5.5.5 and APCu 4.0.2 on CentOS 6.

Thanks!

**Comment by marie-dk** [comment]
@xathien, I just upgraded from php 5.4 to 5.6 and find my self missing those two functions as well... Did you go for [hidef](https://pecl.php.net/package/hidef) instead, or something else?

**Comment by xathien** [comment]
Yep, just ended up running with hidef.

**Comment by marie-dk** [comment]
Thanks... :-)
