### ISSUE TITLE
apc compatibility

### ISSUE THREAD

**Issue by Stricted** [krakjoe/apcu#64]
4.0.3
and this output

            [0] => Array
                (
                    [key] => WCF_409f75bc6a_wbb_BoardModeratorPermission-fb64df1fae01656a495d95af9e4181e5f100104f
                    [ttl] => 259200
                    [nhits] => 0
                    [mtime] => 1390835810
                    [ctime] => 1390835810
                    [dtime] => 0
                    [atime] => 1390835810
                    [ref_count] => 0
                    [mem_size] => 584
                )

its not compatible with the old apc api

**Comment by krakjoe** [comment]
Closing, because housework, and should be resolved, as mentioned.
