### ISSUE TITLE
Apache hunged on futex call for new processes

### ISSUE THREAD

**Issue by pstorralba** [krakjoe/apcu#65]
Hi,

We are experiencing a lock down on apache processes related to APCu (actually we had the very same problem with APC 3.0.1 with PHP 5.2.10). Our current versions are:

- apache 2.2.3 (running on RHEL 5.7)
- PHP 5.4.24
- APCu 4.0.3 (both PHP and APCu are installed with remi packages from http://rpms.famillecollet.com/enterprise/5/remi/).

We have a somehow loaded server whose apc panel shows as follow:
![apcu](https://f.cloud.github.com/assets/257327/2099730/da2bbc3e-8f3f-11e3-90a5-b97d15b7c75b.jpg)

There you can see the configuration and number of requests it had till it locked. The time it takes to lock varies a lot. Sometimes it just takes 5 minutes and some others it resists 20, 30 minutes or even almost 2 hours, with the same load.

The behavior is such that once some critical condition we can't identify occurs, any new apache process gets hung in the futex_wait call (as seen witch strace), as if it was never to be released because the first parameter in the futex_wait call is the same for all of them. We can kill those processes, but it isn't till we restart the whole apache that the problem disappear because any new request is stuck the same way as long as it uses APC cache. 

As an additional information, almost all the entries we cache with APC have a 0 ttl as we want them to stay there forever as they don't change. We are also using OpCache for the opcodes.

After reading about similar problems we got to some ideas like the one stated in http://notmysock.org/blog/php/user-cache-timebomb.html so we changed all apc_store calls for apc_add ones with no success.

We know this isn't too much information to track the bug. If there are any other tests you want us to do, just tell us.

Thank you very much for your help.

**Comment by krakjoe** [comment]
According to other reports, instability issues were fixed in later versions, upgrade to 4.0.6 or 4.0.7.
