### ISSUE TITLE
Can not compile against phpng

### ISSUE THREAD

**Issue by thestanislav** [krakjoe/apcu#78]
Are there plans to support new zend engine api? I can't compile apcu with phpng right now.
https://wiki.php.net/phpng

**Comment by hwongcom** [comment]
When is it ready?

**Comment by kasparsd** [comment]
@krakjoe What are the known issues with supporting PHP 7?

Here is the output when I try to build it on Debian Wheezy: https://gist.github.com/kasparsd/a2b459285905b0025ad1

**Comment by changloong** [comment]
vote for php7...

**Comment by steffenbrem** [comment]
+1 for this. Any updates on this?

**Comment by Stricted** [comment]
+1 ;)

**Comment by satboy78** [comment]
+1 ;)
I'd like to test symfony2 applications using php7 + apcu

**Comment by swen100** [comment]
:+1:

**Comment by gielwijgergangs** [comment]
Looks like there's quite a lot of tight coupled code to the zval structure of PHP5, especially in apc_cache.c 

@krakjoe do you have any plans on refactoring APCu? Please let us know if we could assist in any way. Tried to refactor the code in php_apc.c but I'm stuck in apc_cache.c code.

**Comment by ostark** [comment]
@gielwijgergangs
:+1:

**Comment by swen100** [comment]
:+1: vote for php7

**Comment by adrienbrault** [comment]
This would definitely help :)

**Comment by bradallenfisher** [comment]
:+1:  for php7

**Comment by torstahl** [comment]
also vote for php7 
Please!

**Comment by btopro** [comment]
php7 ftw :+1:

**Comment by layanto** [comment]
+1

**Comment by jlamer** [comment]
:+1:

**Comment by onethumb** [comment]
:+1:

**Comment by neclimdul** [comment]
Every time someone +1 an issue you spam everyone who has politely clicked subscribe and is waiting for updates. Please stop.

**Comment by marcelsud** [comment]
:+1:

**Comment by devdrops** [comment]
:+1: indeed!

**Comment by Stricted** [comment]
https://github.com/krakjoe/apcu/commits/seven ...

**Comment by krakjoe** [comment]
Please don't use that yet ... WIP ... I'll holla when testing should commence ... kthnx.

**Comment by helmuthva** [comment]
+1

**Comment by krakjoe** [comment]
holla ...

**Comment by krakjoe** [comment]
Closing, because ...

**Comment by sebastien-fauvel** [comment]
:+1: what's the status of this issue? I've just installed `php70` and `php70-apcu` with homebrew, and end with a `Fatal error: Uncaught Error: Call to undefined function apc_fetch()`...

The extension seems to be installed correctly, though:
```
$ /usr/local/bin/php -v
PHP 7.0.0 (cli) (built: Dec  2 2015 13:05:57) ( NTS )
Copyright (c) 1997-2015 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2015 Zend Technologies

$ /usr/local/bin/php -i | grep apc
Additional .ini files parsed => /usr/local/etc/php/7.0/conf.d/ext-apcu.ini,
apcu
MMAP File Mask => /tmp/apc.H4LqMG
apc.coredump_unmap => Off => Off
apc.enable_cli => On => On
apc.enabled => On => On
apc.entries_hint => 4096 => 4096
apc.gc_ttl => 3600 => 3600
apc.mmap_file_mask => /tmp/apc.H4LqMG => /tmp/apc.H4LqMG
apc.preload_path => no value => no value
apc.serializer => php => php
apc.shm_segments => 1 => 1
apc.shm_size => 64M => 64M
apc.slam_defense => On => On
apc.smart => 0 => 0
apc.ttl => 7200 => 7200
apc.use_request_time => On => On
apc.writable => /tmp => /tmp

$ /usr/local/bin/php -a
Interactive shell

php > apc_fetch();
PHP Warning:  Uncaught Error: Call to undefined function apc_fetch() in php shell code:1
Stack trace:
#0 {main}
  thrown in php shell code on line 1

Warning: Uncaught Error: Call to undefined function apc_fetch() in php shell code:1
Stack trace:
#0 {main}
  thrown in php shell code on line 1
```

**Comment by remicollet** [comment]
You forget the build option to enable the compat extension (--enable-apcu-bc)

**Comment by sebastien-fauvel** [comment]
Oh, so it's `apcu_fetch` now, and `--enable-apcu-bc` creates an alias for `apc_fetch`?! Ok, merci Rémi!

**Comment by krakjoe** [comment]
Just so everyone is clear on what is going on and why ...

It was always the case that ```apcu_fetch``` and other API's were registered with apcu prefix. 

In PHP5 we were able to register an "apc" extension and provide ```apc_fetch``` and other APIs. In PHP7, because of limitations of new HashTable and or initialization of modules (depending on who you want to blame), we can't register the extension automatically any more.

So in PHP7 we build the apc module separately from apcu module so that you can load it by configuration and register it yourself ...

**Comment by sebastien-fauvel** [comment]
Thanks for the clarification, very much appreciated! Btw, I wasn't aware that `apcu_fetch` was already registered in php5. This definitely helps preparing the migration to php7! I can see the [docs](http://php.net/manual/en/book.apcu.php) have been updated already – it's been a while I hadn't taken a look at it... Thank you once again for your prompt explanations!

**Comment by amcsi** [comment]
@krakjoe so how do I make sure `apc_fetch` works in PHP 7? I tried PECL loading (after `apcu`) both `apc` and `apcu_bc-1.0.0` and neither seem to be providing the `apc_fetch` function.

**Comment by steffenbrem** [comment]
@amcsi The order that you load `apc` and `apcu` is important. You need `apcu.so` to be loaded first:
```ini
; php/conf.d/ext-apc.ini
extension=apcu.so
extension=apc.so
```

**Comment by strarsis** [comment]
I can successfully build latest apcu from PECL, but not latest APC which fails to build with PHP7.
And building apcu does not also result in a apc.so.

With best regards

**Comment by yellow1912** [comment]
Anyone tested this with Symfony 2? Do you need the backward compat module as well? (https://github.com/krakjoe/apcu-bc )

**Comment by amcsi** [comment]
@steffenbrem but it's not this project that I need, do I? https://pecl.php.net/package/APC

I'm going to need this one, right? https://pecl.php.net/package/apcu_bc/1.0.0
Just its filename is apc.so by default rather than apcu_bc.so

**Comment by steffenbrem** [comment]
I've you are familiar with Docker, this is what I use:

```bash
# install apcu for php7
RUN cd /opt && git clone https://github.com/krakjoe/apcu && \
    cd apcu && \
    phpize && \
    ./configure --enable-apcu && \
    make && make install && \
    echo "extension=apcu.so" > /usr/local/etc/php/conf.d/ext-apcu.ini
RUN cd /opt && git clone https://github.com/krakjoe/apcu-bc && \
    cd apcu-bc && \
    phpize && \
    ./configure --enable-apc && \
    make && make install && \
    echo "\nextension=apc.so" >> /usr/local/etc/php/conf.d/ext-apcu.ini
```

I do not use the packages from pecl.

**Comment by krakjoe** [comment]
PHP5
====

apcu.so registers the apc module and functions.

PHP7
====

apcu.so is required by apc.so (provided by apcu_bc package/apcu-bc repo).

I'm going to end this conversation here, to avoid confusion. If you have a new problem, open a new issue.
