### ISSUE TITLE
apc.php - [Delete Now] doesn't work in cache view.

### ISSUE THREAD

**Issue by strangeloopgames** [krakjoe/apcu#82]
There seems to be an undefined index error on this line:

`echo '[<a href="', $MY_SELF, '&OB=', $MYREQUEST['OB'], '&DU=', urlencode($entry[$fieldkey]), '">Delete Now</a>]';`

**Comment by jensk** [comment]
Would be awesome if this could be fixed.

**Comment by Stricted** [comment]
see https://github.com/krakjoe/apcu/commit/f4fc8b9c1e839463d4c8956c0da6bfd9c3e9611b
