### ISSUE TITLE
Clear cache by prefix

### ISSUE THREAD

**Issue by JoyceBabu** [krakjoe/apcu#84]
Is there an option to clear cache by prefix similar to the `xcache_unset_by_prefix` method in XCache?

**Comment by JoyceBabu** [comment]
@krakjoe Any plans to  update APCuP to work with PHP 7?

**Comment by krakjoe** [comment]
Open an issue on the repo, I'll get to it when I have time ... I don't know when that will be ...

**Comment by JoyceBabu** [comment]
Thank you. I have created the issue.

**Comment by thelounge-zz** [comment]
ping

APCIterator and apcu_cache_info at least it's 'cache_list' should be disabled on shared hosting and like "opcache.restrict_api" limited to a specific script path

so i have to write my own "inventory" array in apcu itself with locking and so on

apcu is here part of a caching layer using mysql for long-ttls and all that code is needed to reset caches after changes by purge all records and apcu entries starting with "instance_key_modulename" and for purge everything from a instance everything starting with  "instance_key"

**Comment by thelounge-zz** [comment]
"If we want to use a pattern, we have to select every single entry in the cache and match in some way against all keys, this is obviously far less than ideal, the way it works now is ideal" - but currently you have to iterate every single entry in userland and take care of locking at your own which makes it terrible
