### ISSUE TITLE
APCu resets regularly, bad uptime

### ISSUE THREAD

**Issue by povrazor** [krakjoe/apcu#91]
Hi. I'm running APCu, and I only seem to get at most a few hours of uptime before my data is lost. Worst case is minutes, but when things are going well I can get 2 hours. I'm checking this via apc.php included in the source package (and shedding a tear every time my counters reset).

I'm storing more data in APCu now, but this has been happening since I had only 2 variables (a number and a timestamp).

Server is configured as follows:

CentOS 5.11 (64bit)
Apache 2.2.29
MySQL 5.6.17
PHP 5.5.17
DSO w/ Ruid2
OPcache Enabled
APCu 4.0.7
(mostly installed using EasyApache on WHM (no choice with OPcache))

It's worth mentioning this still happened without Ruid2, with fastCGI, optionally with suEXEC, and without OPcache. With the above config, my httpd+php request threads are currently about 26M each (with 8 GB of RAM available), so I think my general config is fine (happy to be told otherwise though).

APCu settings were all defaults, but I did recently bump my RAM to 128M and set a TTL. Some of the caching code I'm writing would benefit from more overall storage.

Let me know what other information you need. I'd be happy to help diagnose this. I'm loving the performance gains I get with APCu. Even with the bad uptime, it helps a lot. 

Is there a log anywhere of APCu start/restarts, errors, etc?

**Comment by bhatpawan** [comment]
Hi, i am also facing same issue my apcu cache is resets regularly but i don't find any solution yet.
Please Help

**Comment by kian** [comment]
This can happen if APC cache fills up.  In my experience, this also happens when Apache is signaled to restart (e.g., by `logrotate`).

**Comment by povrazor** [comment]
In my setup I'm barely using a few MB of half a GB I have set up for it. I'll have to look in to logrotate though. The Apache server uptime is in days, but APC only lasts minutes to hours.

**Comment by marvhh** [comment]
Hi I have the same problem here.
APC Cache Resets at about 50%.

My configuration:
APCu Version	4.0.7
PHP Version	5.4.43
Server Software	Apache2
Shared Memory	1 Segment(s) with 32.0 MBytes 
(mmap memory)

How can I help to fix this problem?

**Comment by marvhh** [comment]
Hi,

adjusting the following values fixed my problem:
kernel.shmall
kernel.shmmax

**Comment by teo1978** [comment]
I have the same issue.
I have non-zero user_ttl, so there's no reason at all why it should ever restart even if it did fill up.

**Comment by povrazor** [comment]
Closing issue. Was for 4.x series.
