### ISSUE TITLE
Is key info?

### ISSUE THREAD

**Issue by szepeviktor** [krakjoe/apcu#98]
I've var_dumped `$entry` in apc.php:
```php
a:9:{s:4:"info";s:3:"foo";s:3:"ttl";i:0;s:8:"num_hits";d:1;s:17:"modification_time";i:1416677293;s:13:"creation_time";i:1416677293;s:13:"deletion_time";i:0;s:11:"access_time";i:1416677293;s:9:"ref_count";i:0;s:8:"mem_size";i:656;}
```
PHP message: PHP Notice:  Undefined index: key in /apc.php on line 1047

`info` is in the dump and `key` is in the code.
Please advise.
PHP 5.5.19

**Comment by kgustine** [comment]
If so, $fieldkey should be removed as it is not used anywhere in the code

**Comment by szepeviktor** [comment]
An apcu developer must be able to decide it.

**Comment by Stricted** [comment]
see https://github.com/krakjoe/apcu/commit/f4fc8b9c1e839463d4c8956c0da6bfd9c3e9611b

**Comment by szepeviktor** [comment]
Thank you.
